coverage:
  status:
    patch:
      default:
        informational: true
    project:
      default:
        only_pulls: true
        informational: true
parsers:
  gcov:
    branch_detection:
      conditional: no
      loop: yes
      method: no
      macro: no
