[project]
name = "donner"
version = "1.0.0"

# Optional, adding this will enable direct links from the documentation
# to your source code.
git_repo_url = "https://github.com/jwmcglynn/donner/"
git_default_branch = "main"

[paths]
compile_commands = "compile_commands.json"
output_dir = "hdoc-output"

[includes]
paths = []
use_system_includes = true

[ignore]
paths = [
  "/third_party/",
  "/external/",
]
ignore_private_members = true

[pages]
homepage = "docs/about_donner.md"
paths = [
  "docs/architecture.md",
  "docs/code_analysis.md",
  "docs/coding_style.md",
  "docs/ecs.md",
  "docs/updating_Sourcegraph.md",
  "docs/updating_WORKSPACE.md",
  "docs/internal/building.md",
  "docs/internal/fuzzing.md",
]

[debug]
dump_json_payload = true
