load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "common",
    hdrs = ["rendering_instance_view.h"],
    visibility = [
        "//src/svg/renderer:__subpackages__",
    ],
    deps = [
        "//src/svg/components",
    ],
)
