/// @file
/// Emits a shader IR program's WGSL, and the entry-point facts a host needs to create a pipeline
/// from it, as build-time artifacts.
///
/// The editor's WebAssembly package is the reason this exists. Constructing a program's WGSL at
/// runtime links the IR and the WGSL emitter into whatever binary does it, which costs the editor
/// package more than its size budget allows for a string that is identical on every run. Emitting
/// at build time keeps the IR module as the single source of truth while the runtime links
/// neither the IR nor the emitters.
///
/// Program-name driven rather than one tool per program: every filter family migrating onto the
/// IR needs the same treatment, and nineteen copies of this file is not a mechanism.
///
/// The committed byte-exact goldens under `tests/testdata` stay as they are. They pin the same
/// `EmitWgsl` output this tool writes, so a golden and a generated artifact that disagreed would
/// fail the program's golden test; keeping the golden a reviewed, committed file is what makes an
/// emitter change visible in a diff.

#include <cstdio>
#include <cstring>
#include <fstream>
#include <string>
#include <string_view>
#include <vector>

#include "donner/gpu/shader/ModuleInterface.h"
#include "donner/gpu/shader/WgslEmitter.h"
#include "donner/gpu/shader/programs/SnapshotUnpremultiply.h"

namespace donner::gpu::shader {
namespace {

/// One program this tool can emit, named as the build files name it.
struct ProgramEntry {
  std::string_view name;                //!< Build-facing program identifier.
  ShaderResult<IrModule> (*build)();    //!< Builder for the program's IR module.
  std::string_view constantsNamespace;  //!< Namespace the generated header declares.
};

/// Programs this tool knows how to emit. A new IR program adds one row.
constexpr ProgramEntry kPrograms[] = {
    {"snapshot_unpremultiply", &programs::BuildSnapshotUnpremultiplyModule,
     "SnapshotUnpremultiply"},
};

/// Writes \p contents to \p path, returning false with a diagnostic on failure.
bool WriteFile(const std::string& path, const std::string& contents) {
  std::ofstream out(path, std::ios::binary | std::ios::trunc);
  if (!out.good()) {
    std::fprintf(stderr, "emit_program_wgsl: cannot open %s for writing\n", path.c_str());
    return false;
  }
  out << contents;
  return out.good();
}

/// The generated header giving a host the entry point and workgroup size without linking the IR.
/// @param entry Program being emitted. @param info Entry point the module declares.
std::string EntryPointHeader(const ProgramEntry& entry, const ComputeEntryPointInfo& info) {
  std::string out;
  out += "#pragma once\n";
  out += "// Generated by donner/gpu/shader/tools:emit_program_wgsl. Do not edit.\n";
  out += "//\n";
  out += "// The entry-point facts a host needs to create this program's compute pipeline. They\n";
  out += "// are generated rather than restated by hand so the pipeline's declared workgroup\n";
  out += "// size cannot drift from the one compiled into the shader - the disagreement the\n";
  out += "// runtime's own check exists to catch.\n";
  out += "\n#include <cstdint>\n#include <string_view>\n\n";
  out += "namespace donner::gpu::shader::generated::";
  out += std::string(entry.constantsNamespace);
  out += " {\n\n";
  out += "/// Name of the compute entry point in the emitted source.\n";
  out += "inline constexpr std::string_view kEntryPoint = \"" + info.name.str() + "\";\n\n";
  out += "/// Workgroup size the entry point declares.\n";
  out +=
      "inline constexpr uint32_t kWorkgroupSizeX = " + std::to_string(info.workgroupSize.x) + ";\n";
  out +=
      "inline constexpr uint32_t kWorkgroupSizeY = " + std::to_string(info.workgroupSize.y) + ";\n";
  out += "inline constexpr uint32_t kWorkgroupSizeZ = " + std::to_string(info.workgroupSize.z) +
         ";\n\n";
  out += "}  // namespace donner::gpu::shader::generated::";
  out += std::string(entry.constantsNamespace);
  out += "\n";
  return out;
}

int Run(std::string_view program, const std::string& wgslPath, const std::string& headerPath) {
  const ProgramEntry* found = nullptr;
  for (const ProgramEntry& entry : kPrograms) {
    if (entry.name == program) {
      found = &entry;
    }
  }
  if (found == nullptr) {
    std::fprintf(stderr, "emit_program_wgsl: unknown program \"%.*s\"\n",
                 static_cast<int>(program.size()), program.data());
    return 1;
  }

  ShaderResult<IrModule> module = found->build();
  if (module.hasError()) {
    std::fprintf(stderr, "emit_program_wgsl: building %.*s failed\n",
                 static_cast<int>(program.size()), program.data());
    return 1;
  }
  ShaderResult<std::string> wgsl = EmitWgsl(module.result());
  if (wgsl.hasError()) {
    std::fprintf(stderr, "emit_program_wgsl: emitting %.*s failed\n",
                 static_cast<int>(program.size()), program.data());
    return 1;
  }

  const std::vector<ComputeEntryPointInfo> entryPoints = ComputeEntryPointsOf(module.result());
  if (entryPoints.size() != 1) {
    std::fprintf(stderr,
                 "emit_program_wgsl: %.*s declares %zu compute entry points; this tool emits "
                 "constants for exactly one\n",
                 static_cast<int>(program.size()), program.data(), entryPoints.size());
    return 1;
  }

  if (!WriteFile(wgslPath, wgsl.result()) ||
      !WriteFile(headerPath, EntryPointHeader(*found, entryPoints.front()))) {
    return 1;
  }
  return 0;
}

}  // namespace
}  // namespace donner::gpu::shader

int main(int argc, char** argv) {
  if (argc != 4) {
    std::fprintf(stderr, "usage: emit_program_wgsl <program> <out.wgsl> <out_constants.h>\n");
    return 1;
  }
  return donner::gpu::shader::Run(argv[1], argv[2], argv[3]);
}
