// Generated by donner::gpu::shader::WgslEmitter. Do not edit.

struct ColorMatrixParams {
  row0: vec4<f32>,
  row1: vec4<f32>,
  row2: vec4<f32>,
  row3: vec4<f32>,
  row4: vec4<f32>,
}

@group(0) @binding(0) var inputTexture: texture_2d<f32>;
@group(0) @binding(1) var outputTexture: texture_storage_2d<rgba8unorm, write>;
@group(0) @binding(2) var<uniform> params: ColorMatrixParams;
@group(0) @binding(3) var<storage, read> bias: array<vec4<f32>>;

@compute @workgroup_size(8, 8, 1)
fn cs_main(@builtin(global_invocation_id) gid: vec3<u32>) {
  let extent = textureDimensions(outputTexture);
  if (((gid.x >= extent.x) || (gid.y >= extent.y))) {
    return;
  }
  let coords = vec2<i32>(gid.xy);
  let source = textureLoad(inputTexture, coords, 0i);
  let biasIndex = select(0u, 1u, (gid.x > gid.y));
  let biasValue = bias[biasIndex];
  let weighted = ((((params.row0 * source.x) + (params.row1 * source.y)) + (params.row2 * source.z)) + (params.row3 * source.w));
  let shifted = (weighted + params.row4);
  let result = saturate((shifted + biasValue));
  textureStore(outputTexture, coords, result);
}
