// Generated by donner::gpu::shader::WgslEmitter. Do not edit.

struct ColorSpaceConvertParams {
  direction: u32,
  pad0: u32,
  pad1: u32,
  pad2: u32,
}

struct ColorTransferTable {
  samples: array<f32, 8192>,
}

@group(0) @binding(0) var inputTexture: texture_2d<f32>;
@group(0) @binding(1) var outputTexture: texture_storage_2d<rgba32float, write>;
@group(0) @binding(2) var<uniform> params: ColorSpaceConvertParams;
@group(0) @binding(3) var<storage, read> transferTable: ColorTransferTable;

fn srgb_channel_to_linear(c: f32) -> f32 {
  var unit: f32 = 0f;
  if ((c > 0f)) {
    unit = min(c, 1f);
  }
  let scaled = (unit * 4095f);
  let index = u32((scaled + 0.5f));
  return transferTable.samples[(index + 0u)];
}

fn linear_channel_to_srgb(c: f32) -> f32 {
  var unit: f32 = 0f;
  if ((c > 0f)) {
    unit = min(c, 1f);
  }
  let scaled = (unit * 4095f);
  let index = u32((scaled + 0.5f));
  return transferTable.samples[(index + 4096u)];
}

@compute @workgroup_size(8, 8, 1)
fn cs_main(@builtin(global_invocation_id) gid: vec3<u32>) {
  let extent = textureDimensions(outputTexture);
  if (((gid.x >= extent.x) || (gid.y >= extent.y))) {
    return;
  }
  let coords = vec2<i32>(gid.xy);
  let source = textureLoad(inputTexture, coords, 0i);
  var straight: vec4<f32> = vec4<f32>(0f);
  if ((source.w > 0f)) {
    straight = vec4<f32>((source.xyz * (1f / source.w)), source.w);
  }
  var color: vec3<f32> = vec3<f32>(0f);
  if ((params.direction == 0u)) {
    color = vec3<f32>(srgb_channel_to_linear(straight.x), srgb_channel_to_linear(straight.y), srgb_channel_to_linear(straight.z));
  } else {
    color = vec3<f32>(linear_channel_to_srgb(straight.x), linear_channel_to_srgb(straight.y), linear_channel_to_srgb(straight.z));
  }
  let result = vec4<f32>((color * straight.w), straight.w);
  textureStore(outputTexture, coords, saturate(result));
}
