// Generated by donner::gpu::shader::WgslEmitter. Do not edit.

struct CompositeParams {
  op: u32,
  pad0: u32,
  pad1: u32,
  pad2: u32,
  k1: f32,
  k2: f32,
  k3: f32,
  k4: f32,
}

@group(0) @binding(0) var sourceTexture: texture_2d<f32>;
@group(0) @binding(1) var destinationTexture: texture_2d<f32>;
@group(0) @binding(2) var outputTexture: texture_storage_2d<rgba8unorm, write>;
@group(0) @binding(3) var<uniform> params: CompositeParams;

@compute @workgroup_size(8, 8, 1)
fn cs_main(@builtin(global_invocation_id) gid: vec3<u32>) {
  let extent = textureDimensions(outputTexture);
  if (((gid.x >= extent.x) || (gid.y >= extent.y))) {
    return;
  }
  let coords = vec2<i32>(gid.xy);
  let source = textureLoad(sourceTexture, coords, 0i);
  let destination = textureLoad(destinationTexture, coords, 0i);
  let remainingSourceAlpha = (1f - source.w);
  let remainingDestinationAlpha = (1f - destination.w);
  var result: vec4<f32> = (source + (destination * remainingSourceAlpha));
  if ((params.op == 1u)) {
    result = (source * destination.w);
  }
  if ((params.op == 2u)) {
    result = (source * remainingDestinationAlpha);
  }
  if ((params.op == 3u)) {
    result = ((source * destination.w) + (destination * remainingSourceAlpha));
  }
  if ((params.op == 4u)) {
    result = ((source * remainingDestinationAlpha) + (destination * remainingSourceAlpha));
  }
  if ((params.op == 5u)) {
    result = (source + destination);
  }
  if ((params.op == 6u)) {
    result = (((((params.k1 * source) * destination) + (params.k2 * source)) + (params.k3 * destination)) + vec4<f32>(params.k4));
  }
  textureStore(outputTexture, coords, saturate(result));
}
