// Generated by donner::gpu::shader::WgslEmitter. Do not edit.

struct FilterColorMatrixParams {
  col0: vec4<f32>,
  col1: vec4<f32>,
  col2: vec4<f32>,
  col3: vec4<f32>,
  col4: vec4<f32>,
}

@group(0) @binding(0) var inputTexture: texture_2d<f32>;
@group(0) @binding(1) var outputTexture: texture_storage_2d<rgba8unorm, write>;
@group(0) @binding(2) var<uniform> params: FilterColorMatrixParams;

@compute @workgroup_size(8, 8, 1)
fn cs_main(@builtin(global_invocation_id) gid: vec3<u32>) {
  let extent = textureDimensions(outputTexture);
  if (((gid.x >= extent.x) || (gid.y >= extent.y))) {
    return;
  }
  let coords = vec2<i32>(gid.xy);
  let source = textureLoad(inputTexture, coords, 0i);
  var straight: vec4<f32> = vec4<f32>(0f);
  if ((source.w > 0f)) {
    straight = vec4<f32>((source.xyz / source.w), source.w);
  } else {
    let offsetAlpha = saturate(params.col4);
    if ((offsetAlpha.w == 0f)) {
      textureStore(outputTexture, coords, vec4<f32>(0f));
      return;
    }
    textureStore(outputTexture, coords, vec4<f32>((offsetAlpha.xyz * offsetAlpha.w), offsetAlpha.w));
    return;
  }
  let weighted = (((((params.col0 * straight.x) + (params.col1 * straight.y)) + (params.col2 * straight.z)) + (params.col3 * straight.w)) + params.col4);
  let clamped = saturate(weighted);
  textureStore(outputTexture, coords, vec4<f32>((clamped.xyz * clamped.w), clamped.w));
}
