// Generated by donner::gpu::shader::WgslEmitter. Do not edit.

@group(0) @binding(0) var outputTexture: texture_storage_2d<rgba8unorm, write>;
@group(0) @binding(1) var<storage, read> values: array<f32>;

fn round_half_away_from_zero(x: f32) -> f32 {
  return (sign(x) * floor((abs(x) + 0.5f)));
}

@compute @workgroup_size(8, 1, 1)
fn cs_main(@builtin(global_invocation_id) gid: vec3<u32>) {
  let x = values[gid.x];
  let rounded = round_half_away_from_zero(x);
  let axes = vec2<f32>((x * 0.25f), (x * -0.25f));
  let axisSigns = sign(axes);
  let axisFloors = floor(axes);
  let straight = saturate(x);
  let linearized = pow(((straight + 0.055f) / 1.055f), 2.4f);
  let curved = pow(vec2<f32>(straight, (1f - straight)), vec2<f32>(2.4f, 2.4f));
  textureStore(outputTexture, vec2<i32>(i32(gid.x), 0i), vec4<f32>(((rounded + 128f) / 255f), (((axisSigns.x * 100f) + 100f) / 255f), ((axisFloors.x + 128f) / 255f), (0.25f * ((linearized + curved.x) + curved.y))));
}
