// Generated by donner::gpu::shader::WgslEmitter. Do not edit.

struct MorphologyParams {
  radiusX: i32,
  radiusY: i32,
  op: u32,
  pad: u32,
}

@group(0) @binding(0) var inputTexture: texture_2d<f32>;
@group(0) @binding(1) var outputTexture: texture_storage_2d<rgba32float, write>;
@group(0) @binding(2) var<uniform> params: MorphologyParams;

@compute @workgroup_size(8, 8, 1)
fn cs_main(@builtin(global_invocation_id) gid: vec3<u32>) {
  let extent = textureDimensions(outputTexture);
  if (((gid.x >= extent.x) || (gid.y >= extent.y))) {
    return;
  }
  let coord = vec2<i32>(gid.xy);
  let size = vec2<i32>(textureDimensions(inputTexture));
  let erode = (params.op == 0u);
  if (((params.radiusX <= 0i) && (params.radiusY <= 0i))) {
    textureStore(outputTexture, coord, textureLoad(inputTexture, coord, 0i));
    return;
  }
  var accum: vec4<f32> = vec4<f32>(0f, 0f, 0f, 0f);
  if (erode) {
    accum = vec4<f32>(1f, 1f, 1f, 1f);
  }
  for (var dy: i32 = (-params.radiusY); (dy <= params.radiusY); dy = (dy + 1i)) {
    for (var dx: i32 = (-params.radiusX); (dx <= params.radiusX); dx = (dx + 1i)) {
      let source = (coord + vec2<i32>(dx, dy));
      if ((((source.x < 0i) || (source.y < 0i)) || ((source.x >= size.x) || (source.y >= size.y)))) {
        if (erode) {
          accum = vec4<f32>(0f, 0f, 0f, 0f);
        }
      } else {
        let sample = textureLoad(inputTexture, source, 0i);
        if (erode) {
          accum = min(accum, sample);
        } else {
          accum = max(accum, sample);
        }
      }
    }
  }
  textureStore(outputTexture, coord, accum);
}
