// Generated by donner::gpu::shader::WgslEmitter. Do not edit.

struct OffsetParams {
  dx: f32,
  dy: f32,
  pad0: u32,
  pad1: u32,
}

@group(0) @binding(0) var inputTexture: texture_2d<f32>;
@group(0) @binding(1) var outputTexture: texture_storage_2d<rgba8unorm, write>;
@group(0) @binding(2) var<uniform> params: OffsetParams;

fn round_half_away_from_zero(x: f32) -> f32 {
  return (sign(x) * floor((abs(x) + 0.5f)));
}

@compute @workgroup_size(8, 8, 1)
fn cs_main(@builtin(global_invocation_id) gid: vec3<u32>) {
  let extent = textureDimensions(outputTexture);
  if (((gid.x >= extent.x) || (gid.y >= extent.y))) {
    return;
  }
  let coords = vec2<i32>(gid.xy);
  let shift = vec2<i32>(i32(round_half_away_from_zero(params.dx)), i32(round_half_away_from_zero(params.dy)));
  let source = (coords - shift);
  let sourceExtent = vec2<i32>(textureDimensions(inputTexture));
  let outside = ((((source.x < 0i) || (source.y < 0i)) || (source.x >= sourceExtent.x)) || (source.y >= sourceExtent.y));
  if (outside) {
    textureStore(outputTexture, coords, vec4<f32>(0f, 0f, 0f, 0f));
  } else {
    textureStore(outputTexture, coords, textureLoad(inputTexture, source, 0i));
  }
}
