// Generated by donner::gpu::shader::WgslEmitter. Do not edit.

struct Uniforms {
  mvp: mat4x4<f32>,
  patternFromPath: mat4x4<f32>,
  viewport: vec2<f32>,
  tileSize: vec2<f32>,
  color: vec4<f32>,
  fillRule: u32,
  paintMode: u32,
  patternOpacity: f32,
  hasClipPolygon: u32,
  hasClipMask: u32,
  _pad0: u32,
  _pad1: u32,
  _pad2: u32,
  yBase: f32,
  hStride: f32,
  hBandCount: u32,
  xBase: f32,
  vStride: f32,
  vBandCount: u32,
  boundingVertexCount: u32,
  _gridPad1: u32,
  clipPolygonPlanes: array<vec4<f32>, 4>,
  boundingVertices: array<vec4<f32>, 4>,
}

struct Band {
  curveStart: u32,
  curveCount: u32,
  yMin: f32,
  yMax: f32,
  xMin: f32,
  xMax: f32,
  _pad0: f32,
  _pad1: f32,
}

struct InstanceTransform {
  row0: vec4<f32>,
  row1: vec4<f32>,
}

struct Quadratic {
  p0: vec2<f32>,
  p1: vec2<f32>,
  p2: vec2<f32>,
}

struct RayCoverage {
  cov: f32,
  wgt: f32,
}

const kNoBand: u32 = 4294967295u;

@group(0) @binding(0) var<uniform> uniforms: Uniforms;
@group(0) @binding(1) var<storage, read> bands: array<Band>;
@group(0) @binding(2) var<storage, read> curveData: array<f32>;
@group(0) @binding(3) var patternTexture: texture_2d<f32>;
@group(0) @binding(4) var patternSampler: sampler;
@group(0) @binding(5) var clipMaskTexture: texture_2d<f32>;
@group(0) @binding(6) var clipMaskSampler: sampler;
@group(0) @binding(7) var<storage, read> instanceTransforms: array<InstanceTransform>;
@group(0) @binding(8) var<storage, read> vBands: array<Band>;
@group(0) @binding(9) var<storage, read> vCurveData: array<f32>;
@group(0) @binding(10) var<storage, read> hBandGrid: array<u32>;
@group(0) @binding(11) var<storage, read> vBandGrid: array<u32>;

fn clip_mask_coverage(pixel_center: vec2<f32>) -> f32 {
  let dims = vec2<i32>(textureDimensions(clipMaskTexture));
  let texel = clamp(vec2<i32>(round((pixel_center - vec2<f32>(0.5f)))), vec2<i32>(0i), (dims - vec2<i32>(1i)));
  let sample = textureLoad(clipMaskTexture, texel, 0i);
  return clamp(((((sample.x + sample.y) + sample.z) + sample.w) * 0.25f), 0f, 1f);
}

fn load_h_curve(index: u32) -> Quadratic {
  let base = (index * 6u);
  var q: Quadratic;
  q.p0 = vec2<f32>(curveData[(base + 0u)], curveData[(base + 1u)]);
  q.p1 = vec2<f32>(curveData[(base + 2u)], curveData[(base + 3u)]);
  q.p2 = vec2<f32>(curveData[(base + 4u)], curveData[(base + 5u)]);
  return q;
}

fn load_v_curve(index: u32) -> Quadratic {
  let base = (index * 6u);
  var q: Quadratic;
  q.p0 = vec2<f32>(vCurveData[(base + 0u)], vCurveData[(base + 1u)]);
  q.p1 = vec2<f32>(vCurveData[(base + 2u)], vCurveData[(base + 3u)]);
  q.p2 = vec2<f32>(vCurveData[(base + 4u)], vCurveData[(base + 5u)]);
  return q;
}

fn solve_quadratic(a: f32, b: f32, c: f32) -> vec2<f32> {
  var roots: vec2<f32> = vec2<f32>(-1f, -1f);
  if ((abs(a) < 1e-04f)) {
    if ((abs(b) > 1e-06f)) {
      let t = ((-c) / b);
      if (((t >= 0f) && (t <= 1f))) {
        roots.x = t;
      }
    }
    return roots;
  }
  let disc = ((b * b) - ((4f * a) * c));
  if ((disc < 0f)) {
    return roots;
  }
  let sqrt_disc = sqrt(disc);
  let q = (-0.5f * (b + select((-sqrt_disc), sqrt_disc, (b >= 0f))));
  let t0 = (q / a);
  let t1 = select((c / q), (((-b) + sqrt_disc) * (0.5f / a)), (abs(q) < 1e-30f));
  if (((t0 >= 0f) && (t0 <= 1f))) {
    roots.x = t0;
  }
  if (((t1 >= 0f) && (t1 <= 1f))) {
    roots.y = t1;
  }
  return roots;
}

fn owns_axis_sample(start: f32, end: f32, sample: f32) -> bool {
  let lo = min(start, end);
  let hi = max(start, end);
  return ((sample >= lo) && (sample < hi));
}

fn accumulateHoriz(slot: u32, sample: vec2<f32>, ppemX: f32) -> RayCoverage {
  var result: RayCoverage;
  result.cov = 0f;
  result.wgt = 0f;
  if ((slot == kNoBand)) {
    return result;
  }
  let band = bands[slot];
  for (var i: u32 = 0u; (i < band.curveCount); i = (i + 1u)) {
    let curve = load_h_curve((band.curveStart + i));
    if ((!owns_axis_sample(curve.p0.y, curve.p2.y, sample.y))) {
      continue;
    }
    let a = ((curve.p0.y - (2f * curve.p1.y)) + curve.p2.y);
    let b = (2f * (curve.p1.y - curve.p0.y));
    let c = (curve.p0.y - sample.y);
    let roots = solve_quadratic(a, b, c);
    for (var k: i32 = 0i; (k < 2i); k = (k + 1i)) {
      let t = select(roots.y, roots.x, (k == 0i));
      if ((t < 0f)) {
        continue;
      }
      let omt = (1f - t);
      let x = ((((omt * omt) * curve.p0.x) + (((2f * omt) * t) * curve.p1.x)) + ((t * t) * curve.p2.x));
      let r = ((x - sample.x) * ppemX);
      let d_dt = (((2f * omt) * (curve.p1.y - curve.p0.y)) + ((2f * t) * (curve.p2.y - curve.p1.y)));
      let s = select(-1f, 1f, (d_dt >= 0f));
      result.cov = (result.cov + (s * saturate((r + 0.5f))));
      result.wgt = max(result.wgt, saturate((1f - (abs(r) * 2f))));
    }
  }
  return result;
}

fn accumulateVert(slot: u32, sample: vec2<f32>, ppemY: f32) -> RayCoverage {
  var result: RayCoverage;
  result.cov = 0f;
  result.wgt = 0f;
  if ((slot == kNoBand)) {
    return result;
  }
  let band = vBands[slot];
  for (var i: u32 = 0u; (i < band.curveCount); i = (i + 1u)) {
    let curve = load_v_curve((band.curveStart + i));
    if ((!owns_axis_sample(curve.p0.x, curve.p2.x, sample.x))) {
      continue;
    }
    let a = ((curve.p0.x - (2f * curve.p1.x)) + curve.p2.x);
    let b = (2f * (curve.p1.x - curve.p0.x));
    let c = (curve.p0.x - sample.x);
    let roots = solve_quadratic(a, b, c);
    for (var k: i32 = 0i; (k < 2i); k = (k + 1i)) {
      let t = select(roots.y, roots.x, (k == 0i));
      if ((t < 0f)) {
        continue;
      }
      let omt = (1f - t);
      let y = ((((omt * omt) * curve.p0.y) + (((2f * omt) * t) * curve.p1.y)) + ((t * t) * curve.p2.y));
      let r = ((y - sample.y) * ppemY);
      let d_dt = (((2f * omt) * (curve.p1.x - curve.p0.x)) + ((2f * t) * (curve.p2.x - curve.p1.x)));
      let s = select(1f, -1f, (d_dt >= 0f));
      result.cov = (result.cov + (s * saturate((r + 0.5f))));
      result.wgt = max(result.wgt, saturate((1f - (abs(r) * 2f))));
    }
  }
  return result;
}

fn calc_coverage(h: RayCoverage, v: RayCoverage) -> f32 {
  let blended = (abs(((h.cov * h.wgt) + (v.cov * v.wgt))) / max((h.wgt + v.wgt), (1f / 65536f)));
  let floor_cov = min(abs(h.cov), abs(v.cov));
  return max(blended, floor_cov);
}

fn sample_in_clip_polygon(pixel_pos: vec2<f32>) -> bool {
  if ((uniforms.hasClipPolygon == 0u)) {
    return true;
  }
  for (var i: u32 = 0u; (i < 4u); i = (i + 1u)) {
    let plane = uniforms.clipPolygonPlanes[i];
    if (((((plane.x * pixel_pos.x) + (plane.y * pixel_pos.y)) + plane.z) < -1e-04f)) {
      return false;
    }
  }
  return true;
}

fn load_bounding_vertex(index: u32) -> vec2<f32> {
  let pair = uniforms.boundingVertices[(index / 2u)];
  return select(pair.xy, pair.zw, ((index % 2u) != 0u));
}

fn fan_polygon_index(vertex_index: u32) -> u32 {
  let triangle = (vertex_index / 3u);
  let corner = (vertex_index % 3u);
  return select((triangle + corner), 0u, (corner == 0u));
}

fn axes_determinant(axes: mat2x2<f32>) -> f32 {
  return ((axes[0u].x * axes[1u].y) - (axes[0u].y * axes[1u].x));
}

fn axes_are_well_conditioned(axes: mat2x2<f32>) -> bool {
  let axis_scale = (length(axes[0u]) * length(axes[1u]));
  let determinant = axes_determinant(axes);
  return (((axis_scale > 0f) && (axis_scale < 1e+30f)) && (abs(determinant) > (axis_scale * 1e-06f)));
}

fn path_from_pixel_delta(axes: mat2x2<f32>, pixel_delta: vec2<f32>) -> vec2<f32> {
  let determinant = axes_determinant(axes);
  return (vec2<f32>(((axes[1u].y * pixel_delta.x) - (axes[1u].x * pixel_delta.y)), (((-axes[0u].y) * pixel_delta.x) + (axes[0u].x * pixel_delta.y))) / determinant);
}

fn pixel_axes(effective_mvp: mat4x4<f32>) -> mat2x2<f32> {
  let pixel_scale = vec2<f32>((uniforms.viewport.x * 0.5f), ((-uniforms.viewport.y) * 0.5f));
  let origin_pixel = ((effective_mvp * vec4<f32>(0f, 0f, 0f, 1f)).xy * pixel_scale);
  let x_axis_pixel = (((effective_mvp * vec4<f32>(1f, 0f, 0f, 1f)).xy * pixel_scale) - origin_pixel);
  let y_axis_pixel = (((effective_mvp * vec4<f32>(0f, 1f, 0f, 1f)).xy * pixel_scale) - origin_pixel);
  return mat2x2<f32>(x_axis_pixel, y_axis_pixel);
}

fn conservative_path_aabb_expansion(axes: mat2x2<f32>) -> f32 {
  let max_component = max(max(abs(axes[0u].x), abs(axes[0u].y)), max(abs(axes[1u].x), abs(axes[1u].y)));
  if ((!((max_component > 0f) && (max_component < 1e+30f)))) {
    return 0f;
  }
  let scaled_axes = mat2x2<f32>((axes[0u] / max_component), (axes[1u] / max_component));
  let scaled_determinant = abs(axes_determinant(scaled_axes));
  if ((!(scaled_determinant > 0f))) {
    return 0f;
  }
  let scaled_frobenius = sqrt((dot(scaled_axes[0u], scaled_axes[0u]) + dot(scaled_axes[1u], scaled_axes[1u])));
  let expansion = ((0.7071068f * scaled_frobenius) / (max_component * scaled_determinant));
  return select(0f, expansion, ((expansion > 0f) && (expansion < 1e+30f)));
}

fn needs_device_aabb_fallback(axes: mat2x2<f32>) -> bool {
  if ((!axes_are_well_conditioned(axes))) {
    return false;
  }
  let orientation = select(-1f, 1f, (axes_determinant(axes) > 0f));
  for (var i: u32 = 0u; (i < uniforms.boundingVertexCount); i = (i + 1u)) {
    let previous = load_bounding_vertex((((i + uniforms.boundingVertexCount) - 1u) % uniforms.boundingVertexCount));
    let position = load_bounding_vertex(i);
    let next = load_bounding_vertex(((i + 1u) % uniforms.boundingVertexCount));
    let incoming = (axes * (position - previous));
    let outgoing = (axes * (next - position));
    let incoming_length = length(incoming);
    let outgoing_length = length(outgoing);
    if ((!((((incoming_length > 1e-06f) && (incoming_length < 1e+30f)) && (outgoing_length > 1e-06f)) && (outgoing_length < 1e+30f)))) {
      return true;
    }
    let incoming_edge = (incoming / incoming_length);
    let outgoing_edge = (outgoing / outgoing_length);
    let incoming_normal = (orientation * vec2<f32>(incoming_edge.y, (-incoming_edge.x)));
    let outgoing_normal = (orientation * vec2<f32>(outgoing_edge.y, (-outgoing_edge.x)));
    let denominator = (1f + dot(incoming_normal, outgoing_normal));
    if ((!(denominator > 1e-06f))) {
      return true;
    }
    let miter = ((0.5f * (incoming_normal + outgoing_normal)) / denominator);
    if ((!(length(miter) <= 2f))) {
      return true;
    }
  }
  return false;
}

fn load_device_aabb_vertex(effective_mvp: mat4x4<f32>, axes: mat2x2<f32>, polygon_index: u32) -> vec2<f32> {
  let pixel_scale = vec2<f32>((uniforms.viewport.x * 0.5f), ((-uniforms.viewport.y) * 0.5f));
  let origin_pixel = ((effective_mvp * vec4<f32>(0f, 0f, 0f, 1f)).xy * pixel_scale);
  var pixel_min: vec2<f32> = vec2<f32>(1e+30f, 1e+30f);
  var pixel_max: vec2<f32> = vec2<f32>(-1e+30f, -1e+30f);
  for (var i: u32 = 0u; (i < uniforms.boundingVertexCount); i = (i + 1u)) {
    let pixel = (origin_pixel + (axes * load_bounding_vertex(i)));
    pixel_min = min(pixel_min, pixel);
    pixel_max = max(pixel_max, pixel);
  }
  let left = ((polygon_index == 0u) || (polygon_index == 3u));
  let top = (polygon_index < 2u);
  let pixel_corner = vec2<f32>(select((pixel_max.x + 0.5f), (pixel_min.x - 0.5f), left), select((pixel_max.y + 0.5f), (pixel_min.y - 0.5f), top));
  return path_from_pixel_delta(axes, (pixel_corner - origin_pixel));
}

fn load_path_aabb_vertex(expansion: f32, polygon_index: u32) -> vec2<f32> {
  var path_min: vec2<f32> = vec2<f32>(1e+30f, 1e+30f);
  var path_max: vec2<f32> = vec2<f32>(-1e+30f, -1e+30f);
  for (var i: u32 = 0u; (i < uniforms.boundingVertexCount); i = (i + 1u)) {
    let position = load_bounding_vertex(i);
    path_min = min(path_min, position);
    path_max = max(path_max, position);
  }
  let left = ((polygon_index == 0u) || (polygon_index == 3u));
  let lower = (polygon_index < 2u);
  return vec2<f32>(select((path_max.x + expansion), (path_min.x - expansion), left), select((path_max.y + expansion), (path_min.y - expansion), lower));
}

fn dilated_bounding_vertex(axes: mat2x2<f32>, polygon_index: u32) -> vec2<f32> {
  let count = uniforms.boundingVertexCount;
  let previous_index = (((polygon_index + count) - 1u) % count);
  let next_index = ((polygon_index + 1u) % count);
  let previous = load_bounding_vertex(previous_index);
  let position = load_bounding_vertex(polygon_index);
  let next = load_bounding_vertex(next_index);
  if ((!axes_are_well_conditioned(axes))) {
    return position;
  }
  let previous_edge = normalize((axes * (position - previous)));
  let next_edge = normalize((axes * (next - position)));
  let orientation = select(-1f, 1f, (axes_determinant(axes) > 0f));
  let previous_normal = (orientation * vec2<f32>(previous_edge.y, (-previous_edge.x)));
  let next_normal = (orientation * vec2<f32>(next_edge.y, (-next_edge.x)));
  let miter_denominator = (1f + dot(previous_normal, next_normal));
  let pixel_delta = ((0.5f * (previous_normal + next_normal)) / miter_denominator);
  return (position + path_from_pixel_delta(axes, pixel_delta));
}

fn effective_bounding_vertex(effective_mvp: mat4x4<f32>, vertex_index: u32) -> vec2<f32> {
  let axes = pixel_axes(effective_mvp);
  let path_aabb_expansion = conservative_path_aabb_expansion(axes);
  let use_path_aabb = ((!axes_are_well_conditioned(axes)) && (path_aabb_expansion > 0f));
  let use_device_aabb = needs_device_aabb_fallback(axes);
  let use_aabb = (use_path_aabb || use_device_aabb);
  let effective_count = select(uniforms.boundingVertexCount, 4u, use_aabb);
  let triangle = (vertex_index / 3u);
  var polygon_index: u32 = 0u;
  if ((triangle < (effective_count - 2u))) {
    polygon_index = fan_polygon_index(vertex_index);
  }
  if (use_path_aabb) {
    return load_path_aabb_vertex(path_aabb_expansion, polygon_index);
  }
  if (use_device_aabb) {
    return load_device_aabb_vertex(effective_mvp, axes, polygon_index);
  }
  return dilated_bounding_vertex(axes, polygon_index);
}

struct vs_main_Output {
  @builtin(position) clip_pos: vec4<f32>,
  @location(0) sample_pos: vec2<f32>,
}

@vertex
fn vs_main(@builtin(vertex_index) vertex_index: u32, @builtin(instance_index) instance_index: u32) -> vs_main_Output {
  let xf = instanceTransforms[instance_index];
  let instance_mat = mat4x4<f32>(vec4<f32>(xf.row0.x, xf.row1.x, 0f, 0f), vec4<f32>(xf.row0.y, xf.row1.y, 0f, 0f), vec4<f32>(0f, 0f, 1f, 0f), vec4<f32>(xf.row0.z, xf.row1.z, 0f, 1f));
  let effective_mvp = (uniforms.mvp * instance_mat);
  let dilated = effective_bounding_vertex(effective_mvp, vertex_index);
  return vs_main_Output((effective_mvp * vec4<f32>(dilated, 0f, 1f)), dilated);
}

struct fs_main_Output {
  @location(0) color: vec4<f32>,
}

@fragment
fn fs_main(@builtin(position) clip_pos: vec4<f32>, @location(0) sample_pos: vec2<f32>) -> fs_main_Output {
  let pixel_center = clip_pos.xy;
  let ppem = (1f / fwidth(sample_pos));
  var hCov: RayCoverage;
  hCov.cov = 0f;
  hCov.wgt = 0f;
  if ((uniforms.hBandCount > 0u)) {
    let hi = clamp(i32(((sample_pos.y - uniforms.yBase) / uniforms.hStride)), 0i, (i32(uniforms.hBandCount) - 1i));
    let slot = hBandGrid[hi];
    hCov = accumulateHoriz(slot, sample_pos, ppem.x);
  }
  var vCov: RayCoverage;
  vCov.cov = 0f;
  vCov.wgt = 0f;
  if ((uniforms.vBandCount > 0u)) {
    let vj = clamp(i32(((sample_pos.x - uniforms.xBase) / uniforms.vStride)), 0i, (i32(uniforms.vBandCount) - 1i));
    let slot = vBandGrid[vj];
    vCov = accumulateVert(slot, sample_pos, ppem.y);
  }
  var coverage: f32 = calc_coverage(hCov, vCov);
  if ((uniforms.fillRule == 0u)) {
    coverage = saturate(coverage);
  } else {
    coverage = (1f - abs((1f - (fract((coverage * 0.5f)) * 2f))));
  }
  if ((!sample_in_clip_polygon(pixel_center))) {
    coverage = 0f;
  }
  var clipCoverage: f32 = 1f;
  if ((uniforms.hasClipMask != 0u)) {
    clipCoverage = clip_mask_coverage(pixel_center);
  }
  coverage = (coverage * clipCoverage);
  if ((coverage <= 0f)) {
    discard;
  }
  if ((uniforms.paintMode == 0u)) {
    return fs_main_Output((uniforms.color * coverage));
  }
  let patternPos = (uniforms.patternFromPath * vec4<f32>(sample_pos, 0f, 1f)).xy;
  let wrapped = vec2<f32>((fract((patternPos.x / uniforms.tileSize.x)) * uniforms.tileSize.x), (fract((patternPos.y / uniforms.tileSize.y)) * uniforms.tileSize.y));
  let uv = (wrapped / uniforms.tileSize);
  var sampled: vec4<f32> = textureSample(patternTexture, patternSampler, uv);
  sampled = ((sampled * uniforms.patternOpacity) * coverage);
  return fs_main_Output(sampled);
}
