// Generated by donner::gpu::shader::WgslEmitter. Do not edit.

struct Uniforms {
  mvp: mat4x4<f32>,
  patternFromPath: mat4x4<f32>,
  viewport: vec2<f32>,
  tileSize: vec2<f32>,
  color: vec4<f32>,
  fillRule: u32,
  paintMode: u32,
  patternOpacity: f32,
  hasClipPolygon: u32,
  hasClipMask: u32,
  _pad0: u32,
  _pad1: u32,
  _pad2: u32,
  yBase: f32,
  hStride: f32,
  hBandCount: u32,
  xBase: f32,
  vStride: f32,
  vBandCount: u32,
  _gridPad0: u32,
  _gridPad1: u32,
  clipPolygonPlanes: array<vec4<f32>, 4>,
}

struct Band {
  curveStart: u32,
  curveCount: u32,
  yMin: f32,
  yMax: f32,
  xMin: f32,
  xMax: f32,
  _pad0: f32,
  _pad1: f32,
}

struct InstanceTransform {
  row0: vec4<f32>,
  row1: vec4<f32>,
}

struct Quadratic {
  p0: vec2<f32>,
  p1: vec2<f32>,
  p2: vec2<f32>,
}

struct RayCoverage {
  cov: f32,
  wgt: f32,
}

const kNoBand: u32 = 4294967295u;

@group(0) @binding(0) var<uniform> uniforms: Uniforms;
@group(0) @binding(1) var<storage, read> bands: array<Band>;
@group(0) @binding(2) var<storage, read> curveData: array<f32>;
@group(0) @binding(3) var patternTexture: texture_2d<f32>;
@group(0) @binding(4) var patternSampler: sampler;
@group(0) @binding(5) var clipMaskTexture: texture_2d<f32>;
@group(0) @binding(6) var clipMaskSampler: sampler;
@group(0) @binding(7) var<storage, read> instanceTransforms: array<InstanceTransform>;
@group(0) @binding(8) var<storage, read> vBands: array<Band>;
@group(0) @binding(9) var<storage, read> vCurveData: array<f32>;
@group(0) @binding(10) var<storage, read> hBandGrid: array<u32>;
@group(0) @binding(11) var<storage, read> vBandGrid: array<u32>;

fn clip_mask_coverage(pixel_center: vec2<f32>) -> f32 {
  let dims = vec2<i32>(textureDimensions(clipMaskTexture));
  let texel = clamp(vec2<i32>(round((pixel_center - vec2<f32>(0.5f)))), vec2<i32>(0i), (dims - vec2<i32>(1i)));
  let sample = textureLoad(clipMaskTexture, texel, 0i);
  return clamp(((((sample.x + sample.y) + sample.z) + sample.w) * 0.25f), 0f, 1f);
}

fn load_h_curve(index: u32) -> Quadratic {
  let base = (index * 6u);
  var q: Quadratic;
  q.p0 = vec2<f32>(curveData[(base + 0u)], curveData[(base + 1u)]);
  q.p1 = vec2<f32>(curveData[(base + 2u)], curveData[(base + 3u)]);
  q.p2 = vec2<f32>(curveData[(base + 4u)], curveData[(base + 5u)]);
  return q;
}

fn load_v_curve(index: u32) -> Quadratic {
  let base = (index * 6u);
  var q: Quadratic;
  q.p0 = vec2<f32>(vCurveData[(base + 0u)], vCurveData[(base + 1u)]);
  q.p1 = vec2<f32>(vCurveData[(base + 2u)], vCurveData[(base + 3u)]);
  q.p2 = vec2<f32>(vCurveData[(base + 4u)], vCurveData[(base + 5u)]);
  return q;
}

fn solve_quadratic(a: f32, b: f32, c: f32) -> vec2<f32> {
  var roots: vec2<f32> = vec2<f32>(-1f, -1f);
  if ((abs(a) < 1e-04f)) {
    if ((abs(b) > 1e-06f)) {
      let t = ((-c) / b);
      if (((t >= 0f) && (t <= 1f))) {
        roots.x = t;
      }
    }
    return roots;
  }
  let disc = ((b * b) - ((4f * a) * c));
  if ((disc < 0f)) {
    return roots;
  }
  let sqrt_disc = sqrt(disc);
  let q = (-0.5f * (b + select((-sqrt_disc), sqrt_disc, (b >= 0f))));
  let t0 = (q / a);
  let t1 = select((c / q), (((-b) + sqrt_disc) * (0.5f / a)), (abs(q) < 1e-30f));
  if (((t0 >= 0f) && (t0 <= 1f))) {
    roots.x = t0;
  }
  if (((t1 >= 0f) && (t1 <= 1f))) {
    roots.y = t1;
  }
  return roots;
}

fn owns_axis_sample(start: f32, end: f32, sample: f32) -> bool {
  let lo = min(start, end);
  let hi = max(start, end);
  return ((sample >= lo) && (sample < hi));
}

fn accumulateHoriz(slot: u32, sample: vec2<f32>, ppemX: f32) -> RayCoverage {
  var result: RayCoverage;
  result.cov = 0f;
  result.wgt = 0f;
  if ((slot == kNoBand)) {
    return result;
  }
  let band = bands[slot];
  for (var i: u32 = 0u; (i < band.curveCount); i = (i + 1u)) {
    let curve = load_h_curve((band.curveStart + i));
    if ((!owns_axis_sample(curve.p0.y, curve.p2.y, sample.y))) {
      continue;
    }
    let a = ((curve.p0.y - (2f * curve.p1.y)) + curve.p2.y);
    let b = (2f * (curve.p1.y - curve.p0.y));
    let c = (curve.p0.y - sample.y);
    let roots = solve_quadratic(a, b, c);
    for (var k: i32 = 0i; (k < 2i); k = (k + 1i)) {
      let t = select(roots.y, roots.x, (k == 0i));
      if ((t < 0f)) {
        continue;
      }
      let omt = (1f - t);
      let x = ((((omt * omt) * curve.p0.x) + (((2f * omt) * t) * curve.p1.x)) + ((t * t) * curve.p2.x));
      let r = ((x - sample.x) * ppemX);
      let d_dt = (((2f * omt) * (curve.p1.y - curve.p0.y)) + ((2f * t) * (curve.p2.y - curve.p1.y)));
      let s = select(-1f, 1f, (d_dt >= 0f));
      result.cov = (result.cov + (s * saturate((r + 0.5f))));
      result.wgt = max(result.wgt, saturate((1f - (abs(r) * 2f))));
    }
  }
  return result;
}

fn accumulateVert(slot: u32, sample: vec2<f32>, ppemY: f32) -> RayCoverage {
  var result: RayCoverage;
  result.cov = 0f;
  result.wgt = 0f;
  if ((slot == kNoBand)) {
    return result;
  }
  let band = vBands[slot];
  for (var i: u32 = 0u; (i < band.curveCount); i = (i + 1u)) {
    let curve = load_v_curve((band.curveStart + i));
    if ((!owns_axis_sample(curve.p0.x, curve.p2.x, sample.x))) {
      continue;
    }
    let a = ((curve.p0.x - (2f * curve.p1.x)) + curve.p2.x);
    let b = (2f * (curve.p1.x - curve.p0.x));
    let c = (curve.p0.x - sample.x);
    let roots = solve_quadratic(a, b, c);
    for (var k: i32 = 0i; (k < 2i); k = (k + 1i)) {
      let t = select(roots.y, roots.x, (k == 0i));
      if ((t < 0f)) {
        continue;
      }
      let omt = (1f - t);
      let y = ((((omt * omt) * curve.p0.y) + (((2f * omt) * t) * curve.p1.y)) + ((t * t) * curve.p2.y));
      let r = ((y - sample.y) * ppemY);
      let d_dt = (((2f * omt) * (curve.p1.x - curve.p0.x)) + ((2f * t) * (curve.p2.x - curve.p1.x)));
      let s = select(1f, -1f, (d_dt >= 0f));
      result.cov = (result.cov + (s * saturate((r + 0.5f))));
      result.wgt = max(result.wgt, saturate((1f - (abs(r) * 2f))));
    }
  }
  return result;
}

fn calc_coverage(h: RayCoverage, v: RayCoverage) -> f32 {
  let blended = (abs(((h.cov * h.wgt) + (v.cov * v.wgt))) / max((h.wgt + v.wgt), (1f / 65536f)));
  let floor_cov = min(abs(h.cov), abs(v.cov));
  return max(blended, floor_cov);
}

fn sample_in_clip_polygon(pixel_pos: vec2<f32>) -> bool {
  if ((uniforms.hasClipPolygon == 0u)) {
    return true;
  }
  for (var i: u32 = 0u; (i < 4u); i = (i + 1u)) {
    let plane = uniforms.clipPolygonPlanes[i];
    if (((((plane.x * pixel_pos.x) + (plane.y * pixel_pos.y)) + plane.z) < -1e-04f)) {
      return false;
    }
  }
  return true;
}

struct vs_main_Output {
  @builtin(position) clip_pos: vec4<f32>,
  @location(0) sample_pos: vec2<f32>,
}

@vertex
fn vs_main(@builtin(instance_index) instance_index: u32, @location(0) pos: vec2<f32>, @location(1) normal: vec2<f32>, @location(2) bandIndex: u32) -> vs_main_Output {
  let xf = instanceTransforms[instance_index];
  let instance_mat = mat4x4<f32>(vec4<f32>(xf.row0.x, xf.row1.x, 0f, 0f), vec4<f32>(xf.row0.y, xf.row1.y, 0f, 0f), vec4<f32>(0f, 0f, 1f, 0f), vec4<f32>(xf.row0.z, xf.row1.z, 0f, 1f));
  let effective_mvp = (uniforms.mvp * instance_mat);
  let world_normal = (effective_mvp * vec4<f32>(normal, 0f, 0f)).xy;
  let viewport_normal = ((world_normal * uniforms.viewport) * 0.5f);
  let viewport_len = length(viewport_normal);
  let d = (1f / max(viewport_len, 0.001f));
  let dilated = (pos + (normal * d));
  return vs_main_Output((effective_mvp * vec4<f32>(dilated, 0f, 1f)), dilated);
}

struct fs_main_Output {
  @location(0) color: vec4<f32>,
}

@fragment
fn fs_main(@builtin(position) clip_pos: vec4<f32>, @location(0) sample_pos: vec2<f32>) -> fs_main_Output {
  let pixel_center = clip_pos.xy;
  let ppem = (1f / fwidth(sample_pos));
  var hCov: RayCoverage;
  hCov.cov = 0f;
  hCov.wgt = 0f;
  if ((uniforms.hBandCount > 0u)) {
    let hi = clamp(i32(((sample_pos.y - uniforms.yBase) / uniforms.hStride)), 0i, (i32(uniforms.hBandCount) - 1i));
    let slot = hBandGrid[hi];
    hCov = accumulateHoriz(slot, sample_pos, ppem.x);
  }
  var vCov: RayCoverage;
  vCov.cov = 0f;
  vCov.wgt = 0f;
  if ((uniforms.vBandCount > 0u)) {
    let vj = clamp(i32(((sample_pos.x - uniforms.xBase) / uniforms.vStride)), 0i, (i32(uniforms.vBandCount) - 1i));
    let slot = vBandGrid[vj];
    vCov = accumulateVert(slot, sample_pos, ppem.y);
  }
  var coverage: f32 = calc_coverage(hCov, vCov);
  if ((uniforms.fillRule == 0u)) {
    coverage = saturate(coverage);
  } else {
    coverage = (1f - abs((1f - (fract((coverage * 0.5f)) * 2f))));
  }
  if ((!sample_in_clip_polygon(pixel_center))) {
    coverage = 0f;
  }
  var clipCoverage: f32 = 1f;
  if ((uniforms.hasClipMask != 0u)) {
    clipCoverage = clip_mask_coverage(pixel_center);
  }
  coverage = (coverage * clipCoverage);
  if ((coverage <= 0f)) {
    discard;
  }
  if ((uniforms.paintMode == 0u)) {
    return fs_main_Output((uniforms.color * coverage));
  }
  let patternPos = (uniforms.patternFromPath * vec4<f32>(sample_pos, 0f, 1f)).xy;
  let wrapped = vec2<f32>((fract((patternPos.x / uniforms.tileSize.x)) * uniforms.tileSize.x), (fract((patternPos.y / uniforms.tileSize.y)) * uniforms.tileSize.y));
  let uv = (wrapped / uniforms.tileSize);
  var sampled: vec4<f32> = textureSample(patternTexture, patternSampler, uv);
  sampled = ((sampled * uniforms.patternOpacity) * coverage);
  return fs_main_Output(sampled);
}
