// Generated by donner::gpu::shader::WgslEmitter. Do not edit.

struct SubregionClipParams {
  invA: f32,
  invB: f32,
  invC: f32,
  invD: f32,
  invE: f32,
  invF: f32,
  userX0: f32,
  userY0: f32,
  userX1: f32,
  userY1: f32,
}

@group(0) @binding(0) var inputTexture: texture_2d<f32>;
@group(0) @binding(1) var outputTexture: texture_storage_2d<rgba8unorm, write>;
@group(0) @binding(2) var<uniform> params: SubregionClipParams;

@compute @workgroup_size(8, 8, 1)
fn cs_main(@builtin(global_invocation_id) gid: vec3<u32>) {
  let extent = textureDimensions(outputTexture);
  if (((gid.x >= extent.x) || (gid.y >= extent.y))) {
    return;
  }
  let coords = vec2<i32>(gid.xy);
  let centerX = (f32(coords.x) + 0.5f);
  let centerY = (f32(coords.y) + 0.5f);
  let userX = (((params.invA * centerX) + (params.invC * centerY)) + params.invE);
  let userY = (((params.invB * centerX) + (params.invD * centerY)) + params.invF);
  let outside = ((((userX < params.userX0) || (userX >= params.userX1)) || (userY < params.userY0)) || (userY >= params.userY1));
  if (outside) {
    textureStore(outputTexture, coords, vec4<f32>(0f, 0f, 0f, 0f));
  } else {
    textureStore(outputTexture, coords, textureLoad(inputTexture, coords, 0i));
  }
}
