load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "filter_effect",
    srcs = [
        "filter_effect.cc",
    ],
    hdrs = [
        "filter_effect.h",
    ],
    visibility = ["//src/svg:__subpackages__"],
    deps = [
        "//src/base",
        "//src/svg/graph",
    ],
)
