load("//build_defs:visibility.bzl", "donner_internal_visibility")
load("//build_defs:rules.bzl", "donner_cc_library")

donner_cc_library(
    name = "element",
    hdrs = [
        "ElementLike.h",
        "ElementTraversalGenerators.h",
    ],
    visibility = donner_internal_visibility(),
    deps = [
        "//donner/base",
    ],
)
