load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "common",
    hdrs = ["RenderingInstanceView.h"],
    visibility = [
        "//donner/svg/renderer:__subpackages__",
    ],
    deps = [
        "//donner/svg/components",
    ],
)
