load("@rules_cc//cc:defs.bzl", "cc_library")
load("//build_defs:package.bzl", "donner_package")

cc_library(
    name = "common",
    hdrs = ["RenderingInstanceView.h"],
    visibility = [
        "//donner/svg/renderer:__subpackages__",
    ],
    deps = [
        "//donner/svg/components",
    ],
)

donner_package()
