/// @file
/// GeoEncoder command-stream captures against `gpu::RecordingDevice` (design 0053 packet 8b).
///
/// Every test drives the migrated Geode recording family (GeodePipeline /
/// GeodeGradientPipeline / GeodeImagePipeline construction, GeoEncoder, and
/// GeodeTextureEncoder) against a pure `donner::gpu::RecordingDevice` - no GPU, no GeodeDevice,
/// and no wgpu anywhere in the test. The committed captures pin the exact command stream each
/// scene records: they are the structural-counter-parity anchor for the later Metal / Vulkan
/// production packets, which must replay these same streams against real backends.
///
/// Golden discipline: captures are generated, never hand-written. Run the test with a stale
/// golden and copy the raw actual capture that `ExpectCaptureEquals` prints from the failure
/// output, then re-run green and review the capture line-by-line (binding sets per pipeline
/// family, one uniform write per draw, dummy binds where expected, zero creates in the resident
/// steady-state frame).

#include <gmock/gmock.h>
#include <gtest/gtest.h>

#include <array>
#include <cstdint>
#include <iostream>
#include <memory>
#include <string>
#include <utility>

#include "donner/base/Box.h"
#include "donner/base/FillRule.h"
#include "donner/base/Path.h"
#include "donner/base/Transform.h"
#include "donner/base/Vector2.h"
#include "donner/css/Color.h"
#include "donner/gpu/CommandEncoder.h"
#include "donner/gpu/RecordingDevice.h"
#include "donner/gpu/tests/GpuTestUtils.h"
#include "donner/svg/renderer/geode/GeoEncoder.h"
#include "donner/svg/renderer/geode/GeodeGpuContext.h"
#include "donner/svg/renderer/geode/GeodeImagePipeline.h"
#include "donner/svg/renderer/geode/GeodePathEncoder.h"
#include "donner/svg/renderer/geode/GeodePipeline.h"
#include "donner/svg/renderer/geode/GeodeResidentPathComponent.h"
#include "donner/svg/renderer/geode/GeodeTextureEncoder.h"
#include "donner/svg/resources/ImageResource.h"

namespace donner::geode {

namespace {

using gpu::GetResultOrFail;
using testing::Eq;
using testing::HasSubstr;
using testing::Not;

constexpr uint32_t kSize = 64;

/// Compares a capture against its committed golden. On mismatch, prints the raw (unescaped)
/// actual capture to stderr so the golden can be regenerated by copy-paste, in addition to
/// gtest's escaped string diff.
void ExpectCaptureEquals(const std::string& actual, const std::string& expected) {
  if (actual != expected) {
    std::cerr << "=== BEGIN actual capture (copy into the golden) ===\n"
              << actual << "=== END actual capture ===\n";
  }
  EXPECT_THAT(actual, Eq(expected));
}

/// Fixture: a fresh `gpu::RecordingDevice` per test (deterministic slot numbering), the shared
/// context dummies created through `GeodeSharedGpuResources::Create` (so labels and payloads
/// match production `GeodeDevice` streams), the three RGBA8 pipelines, and a 64x64 render
/// target. Everything is created through the RecordingDevice; no GeodeDevice, no GPU.
class GeoEncoderRecordingTest : public ::testing::Test {
protected:
  GeoEncoderRecordingTest()
      : shared_(GetResultOrFail(GeodeSharedGpuResources::Create(device_))),
        fillPipeline_(device_, gpu::TextureFormat::RGBA8Unorm),
        gradientPipeline_(device_, gpu::TextureFormat::RGBA8Unorm),
        imagePipeline_(device_, gpu::TextureFormat::RGBA8Unorm),
        target_(GetResultOrFail(device_.createTexture(gpu::TextureDescriptor{
            "RecordingTarget", gpu::Extent2d{kSize, kSize}, gpu::TextureFormat::RGBA8Unorm,
            gpu::TextureUsage::RenderAttachment | gpu::TextureUsage::CopySrc}))) {
    context_.gpuDevice = &device_;
    context_.geodeDevice = nullptr;  // Counters become no-ops; this suite pins streams, not
                                     // counters.
    context_.dummyPatternTextureView = &shared_.dummyPatternTextureView;
    context_.dummyPatternSampler = &shared_.dummyPatternSampler;
    context_.dummyClipMaskTextureView = &shared_.dummyClipMaskTextureView;
    context_.dummyClipMaskSampler = &shared_.dummyClipMaskSampler;
    context_.identityInstanceTransformBuffer = &shared_.identityInstanceTransformBuffer;
  }

  /// Constructs an owned-CommandEncoder-mode GeoEncoder against the fixture target.
  GeoEncoder makeEncoder() {
    return GeoEncoder(context_, fillPipeline_, gradientPipeline_, imagePipeline_, target_,
                      gpu::Extent2d{kSize, kSize});
  }

  gpu::RecordingDevice device_;
  GeodeSharedGpuResources shared_;
  GeodePipeline fillPipeline_;
  GeodeGradientPipeline gradientPipeline_;
  GeodeImagePipeline imagePipeline_;
  gpu::Texture target_;
  GeodeGpuContext context_;
};

/// The shared-resource + pipeline + target preamble every capture starts with. Serialized
/// once here (instead of once per golden) because the fixture creates identical resources in
/// identical order for every test.
std::string FixturePreamble() {
  // clang-format off
  return R"(createTexture texture#0 label="GeodeDeviceDummyPattern" size=1x1 format=RGBA8Unorm usage=Sampled|CopyDst sampleCount=1
writeTexture texture#0 offsetBytes=0 bytesPerRow=256 rowsPerImage=1 writeSize=1x1 byteCount=4 dataHash=4d25077f9dcd5758
createTextureView textureView#0 label="GeodeDeviceDummyPatternView" texture=texture#0
createSampler sampler#0 label="GeodeDeviceDummyPatternSampler" magFilter=Linear minFilter=Linear addressModeU=Repeat addressModeV=Repeat
createTexture texture#1 label="GeodeDeviceDummyClipMask" size=1x1 format=RGBA8Unorm usage=Sampled|CopyDst sampleCount=1
writeTexture texture#1 offsetBytes=0 bytesPerRow=256 rowsPerImage=1 writeSize=1x1 byteCount=4 dataHash=994f76653e2a3951
createTextureView textureView#1 label="GeodeDeviceDummyClipMaskView" texture=texture#1
createSampler sampler#1 label="GeodeDeviceDummyClipMaskSampler" magFilter=Linear minFilter=Linear addressModeU=ClampToEdge addressModeV=ClampToEdge
createBuffer buffer#0 label="GeodeDeviceIdentityInstanceTransform" byteSize=32 usage=Storage|CopyDst
writeBuffer buffer#0 offsetBytes=0 byteCount=32 dataHash=5aa2bb2fb63ec015
createBindGroupLayout bindGroupLayout#0 label="GeodeSlugFillBGL" entries=[{binding=0 visibility=Vertex|Fragment type=UniformBuffer} {binding=1 visibility=Fragment type=ReadOnlyStorageBuffer} {binding=2 visibility=Fragment type=ReadOnlyStorageBuffer} {binding=3 visibility=Fragment type=SampledTexture2dFloat} {binding=4 visibility=Fragment type=FilteringSampler} {binding=5 visibility=Fragment type=SampledTexture2dFloat} {binding=6 visibility=Fragment type=FilteringSampler} {binding=7 visibility=Vertex type=ReadOnlyStorageBuffer} {binding=8 visibility=Fragment type=ReadOnlyStorageBuffer} {binding=9 visibility=Fragment type=ReadOnlyStorageBuffer} {binding=10 visibility=Fragment type=ReadOnlyStorageBuffer} {binding=11 visibility=Fragment type=ReadOnlyStorageBuffer}]
createPipelineLayout pipelineLayout#0 label="GeodeSlugFillPL" bindGroupLayouts=[bindGroupLayout#0]
createShaderModule shaderModule#0 label="SlugFill" sourceKind=Wgsl sourceBytes=17219 sourceHash=fa0736baddaec7cd
createRenderPipeline renderPipeline#0 label="GeodeSlugFill" layout=pipelineLayout#0 vertex={module=shaderModule#0 entryPoint="vs_main" buffers=[{strideBytes=20 stepMode=Vertex attributes=[{format=Float32x2 offsetBytes=0 shaderLocation=0} {format=Float32x2 offsetBytes=8 shaderLocation=1} {format=Uint32 offsetBytes=16 shaderLocation=2}]}]} fragment={module=shaderModule#0 entryPoint="fs_main" targets=[{format=RGBA8Unorm blend={color={srcFactor=One dstFactor=OneMinusSrcAlpha operation=Add} alpha={srcFactor=One dstFactor=OneMinusSrcAlpha operation=Add}} writeMask=Red|Green|Blue|Alpha}]} topology=TriangleList cullMode=None multisampleCount=1
createBindGroupLayout bindGroupLayout#1 label="GeodeSlugGradientBGL" entries=[{binding=0 visibility=Vertex|Fragment type=UniformBuffer} {binding=1 visibility=Fragment type=ReadOnlyStorageBuffer} {binding=2 visibility=Fragment type=ReadOnlyStorageBuffer} {binding=3 visibility=Fragment type=SampledTexture2dFloat} {binding=4 visibility=Fragment type=FilteringSampler} {binding=5 visibility=Fragment type=ReadOnlyStorageBuffer} {binding=6 visibility=Fragment type=ReadOnlyStorageBuffer} {binding=7 visibility=Fragment type=ReadOnlyStorageBuffer} {binding=8 visibility=Fragment type=ReadOnlyStorageBuffer}]
createPipelineLayout pipelineLayout#1 label="GeodeSlugGradientPL" bindGroupLayouts=[bindGroupLayout#1]
createShaderModule shaderModule#1 label="SlugGradient" sourceKind=Wgsl sourceBytes=13730 sourceHash=52635773eb418f8e
createRenderPipeline renderPipeline#1 label="GeodeSlugGradient" layout=pipelineLayout#1 vertex={module=shaderModule#1 entryPoint="vs_main" buffers=[{strideBytes=20 stepMode=Vertex attributes=[{format=Float32x2 offsetBytes=0 shaderLocation=0} {format=Float32x2 offsetBytes=8 shaderLocation=1} {format=Uint32 offsetBytes=16 shaderLocation=2}]}]} fragment={module=shaderModule#1 entryPoint="fs_main" targets=[{format=RGBA8Unorm blend={color={srcFactor=One dstFactor=OneMinusSrcAlpha operation=Add} alpha={srcFactor=One dstFactor=OneMinusSrcAlpha operation=Add}} writeMask=Red|Green|Blue|Alpha}]} topology=TriangleList cullMode=None multisampleCount=1
createBindGroupLayout bindGroupLayout#2 label="GeodeImageBlitBGL" entries=[{binding=0 visibility=Vertex|Fragment type=UniformBuffer} {binding=1 visibility=Fragment type=FilteringSampler} {binding=2 visibility=Fragment type=SampledTexture2dFloat} {binding=3 visibility=Fragment type=SampledTexture2dFloat} {binding=4 visibility=Fragment type=SampledTexture2dFloat} {binding=5 visibility=Fragment type=SampledTexture2dFloat} {binding=6 visibility=Fragment type=FilteringSampler}]
createPipelineLayout pipelineLayout#2 label="GeodeImageBlitPL" bindGroupLayouts=[bindGroupLayout#2]
createShaderModule shaderModule#2 label="ImageBlit" sourceKind=Wgsl sourceBytes=17105 sourceHash=b3063501af3e4cc2
createRenderPipeline renderPipeline#2 label="GeodeImageBlit" layout=pipelineLayout#2 vertex={module=shaderModule#2 entryPoint="vs_main" buffers=[]} fragment={module=shaderModule#2 entryPoint="fs_main" targets=[{format=RGBA8Unorm blend={color={srcFactor=One dstFactor=OneMinusSrcAlpha operation=Add} alpha={srcFactor=One dstFactor=OneMinusSrcAlpha operation=Add}} writeMask=Red|Green|Blue|Alpha}]} topology=TriangleList cullMode=None multisampleCount=1
createSampler sampler#2 label="GeodeImageBlitLinear" magFilter=Linear minFilter=Linear addressModeU=ClampToEdge addressModeV=ClampToEdge
createSampler sampler#3 label="GeodeImageBlitNearest" magFilter=Nearest minFilter=Nearest addressModeU=ClampToEdge addressModeV=ClampToEdge
createSampler sampler#4 label="GeodeImageBlitClipMask" magFilter=Linear minFilter=Linear addressModeU=ClampToEdge addressModeV=ClampToEdge
createTexture texture#2 label="RecordingTarget" size=64x64 format=RGBA8Unorm usage=RenderAttachment|CopySrc sampleCount=1
)";
  // clang-format on
}

// ----------------------------------------------------------------------------

/// Scene 1: clear + setTransform + solid fill of an axis-aligned rect.
TEST_F(GeoEncoderRecordingTest, SolidFill) {
  Path path = PathBuilder().addRect(Box2d({16, 16}, {48, 48})).build();

  GeoEncoder encoder = makeEncoder();
  encoder.clear(css::RGBA(255, 255, 255, 255));
  encoder.setTransform(Transform2d::Translate(2.0, 4.0));
  encoder.fillPath(path, css::RGBA(255, 0, 0, 255), FillRule::NonZero);
  encoder.finish();

  // clang-format off
  const std::string kExpected = FixturePreamble() + R"(createTextureView textureView#2 label="GeoEncoderTarget" texture=texture#2
createBuffer buffer#1 label="GeodeVertexArena" byteSize=65536 usage=Vertex|CopyDst
writeBuffer buffer#1 offsetBytes=0 byteCount=120 dataHash=36ff4236ea0065f5
createBuffer buffer#2 label="GeodeBandArena" byteSize=65536 usage=Storage|CopyDst
writeBuffer buffer#2 offsetBytes=0 byteCount=32 dataHash=c6fd1e2a3b928a36
createBuffer buffer#3 label="GeodeCurveArena" byteSize=65536 usage=Storage|CopyDst
writeBuffer buffer#3 offsetBytes=0 byteCount=72 dataHash=b4ead2ffbd88266c
createBuffer buffer#4 label="GeodeVBandArena" byteSize=65536 usage=Storage|CopyDst
writeBuffer buffer#4 offsetBytes=0 byteCount=32 dataHash=c6fd1e2a3b928a36
createBuffer buffer#5 label="GeodeVCurveArena" byteSize=65536 usage=Storage|CopyDst
writeBuffer buffer#5 offsetBytes=0 byteCount=72 dataHash=467c6868522c325c
createBuffer buffer#6 label="GeodeHGridArena" byteSize=65536 usage=Storage|CopyDst
writeBuffer buffer#6 offsetBytes=0 byteCount=4 dataHash=4d25767f9dce13f5
createBuffer buffer#7 label="GeodeVGridArena" byteSize=65536 usage=Storage|CopyDst
writeBuffer buffer#7 offsetBytes=0 byteCount=4 dataHash=4d25767f9dce13f5
createBuffer buffer#8 label="GeodeUniformArena" byteSize=65536 usage=Uniform|CopyDst
writeBuffer buffer#8 offsetBytes=0 byteCount=288 dataHash=7c6aa93252320119
createBindGroup bindGroup#0 label="GeodeBindGroup" layout=bindGroupLayout#0 entries=[{binding=0 buffer=buffer#8 offsetBytes=0 sizeBytes=288} {binding=1 buffer=buffer#2 offsetBytes=0 sizeBytes=32} {binding=2 buffer=buffer#3 offsetBytes=0 sizeBytes=72} {binding=3 textureView=textureView#0} {binding=4 sampler=sampler#0} {binding=5 textureView=textureView#1} {binding=6 sampler=sampler#1} {binding=7 buffer=buffer#0 offsetBytes=0 sizeBytes=32} {binding=8 buffer=buffer#4 offsetBytes=0 sizeBytes=32} {binding=9 buffer=buffer#5 offsetBytes=0 sizeBytes=72} {binding=10 buffer=buffer#6 offsetBytes=0 sizeBytes=4} {binding=11 buffer=buffer#7 offsetBytes=0 sizeBytes=4}]
submit serial=1 commandBuffer#0 commandCount=7
  beginRenderPass label="GeoEncoderPass" colorAttachments=[{view=textureView#2 loadOp=Clear storeOp=Store clearColor=(1 1 1 1)}]
  setScissorRect x=0 y=0 width=64 height=64
  setPipeline renderPipeline#0
  setVertexBuffer slot=0 buffer=buffer#1 offsetBytes=0
  setBindGroup index=0 bindGroup=bindGroup#0
  draw vertexCount=6 instanceCount=1 firstVertex=0 firstInstance=0
  endRenderPass
)";
  // clang-format on
  ExpectCaptureEquals(device_.serialize(), kExpected);
}

/// Scene 2: one encode drawn at three instance transforms in a single instanced draw.
TEST_F(GeoEncoderRecordingTest, InstancedFill) {
  Path path = PathBuilder().addRect(Box2d({0, 0}, {8, 8})).build();
  const EncodedPath encoded = GeodePathEncoder::encode(path, FillRule::NonZero);

  // Three instances packed as two vec4f rows each (row-major affine): identity plus two
  // translations, matching the WGSL `InstanceTransform` wire format.
  // clang-format off
  const float kInstanceTransforms[24] = {
      1.0f, 0.0f, 0.0f,  0.0f, 0.0f, 1.0f, 0.0f,  0.0f,
      1.0f, 0.0f, 16.0f, 0.0f, 0.0f, 1.0f, 0.0f,  0.0f,
      1.0f, 0.0f, 0.0f,  0.0f, 0.0f, 1.0f, 16.0f, 0.0f,
  };
  // clang-format on

  GeoEncoder encoder = makeEncoder();
  encoder.clear(css::RGBA(0, 0, 0, 255));
  encoder.fillPathInstanced(encoded, css::RGBA(0, 128, 255, 255), FillRule::NonZero,
                            kInstanceTransforms);
  encoder.finish();

  // clang-format off
  const std::string kExpected = FixturePreamble() + R"(createTextureView textureView#2 label="GeoEncoderTarget" texture=texture#2
createBuffer buffer#1 label="GeodeInstanceTransformArena" byteSize=65536 usage=Storage|CopyDst
writeBuffer buffer#1 offsetBytes=0 byteCount=96 dataHash=5be730832f9cd4b5
createBuffer buffer#2 label="GeodeVertexArena" byteSize=65536 usage=Vertex|CopyDst
writeBuffer buffer#2 offsetBytes=0 byteCount=120 dataHash=30f70c702b9ed415
createBuffer buffer#3 label="GeodeBandArena" byteSize=65536 usage=Storage|CopyDst
writeBuffer buffer#3 offsetBytes=0 byteCount=32 dataHash=af165935afc55476
createBuffer buffer#4 label="GeodeCurveArena" byteSize=65536 usage=Storage|CopyDst
writeBuffer buffer#4 offsetBytes=0 byteCount=72 dataHash=b2019a7896ef8065
createBuffer buffer#5 label="GeodeVBandArena" byteSize=65536 usage=Storage|CopyDst
writeBuffer buffer#5 offsetBytes=0 byteCount=32 dataHash=af165935afc55476
createBuffer buffer#6 label="GeodeVCurveArena" byteSize=65536 usage=Storage|CopyDst
writeBuffer buffer#6 offsetBytes=0 byteCount=72 dataHash=6e3ed8f2333417e5
createBuffer buffer#7 label="GeodeHGridArena" byteSize=65536 usage=Storage|CopyDst
writeBuffer buffer#7 offsetBytes=0 byteCount=4 dataHash=4d25767f9dce13f5
createBuffer buffer#8 label="GeodeVGridArena" byteSize=65536 usage=Storage|CopyDst
writeBuffer buffer#8 offsetBytes=0 byteCount=4 dataHash=4d25767f9dce13f5
createBuffer buffer#9 label="GeodeUniformArena" byteSize=65536 usage=Uniform|CopyDst
writeBuffer buffer#9 offsetBytes=0 byteCount=288 dataHash=99b38ece4bd5ae61
createBindGroup bindGroup#0 label="GeodeBindGroup" layout=bindGroupLayout#0 entries=[{binding=0 buffer=buffer#9 offsetBytes=0 sizeBytes=288} {binding=1 buffer=buffer#3 offsetBytes=0 sizeBytes=32} {binding=2 buffer=buffer#4 offsetBytes=0 sizeBytes=72} {binding=3 textureView=textureView#0} {binding=4 sampler=sampler#0} {binding=5 textureView=textureView#1} {binding=6 sampler=sampler#1} {binding=7 buffer=buffer#1 offsetBytes=0 sizeBytes=96} {binding=8 buffer=buffer#5 offsetBytes=0 sizeBytes=32} {binding=9 buffer=buffer#6 offsetBytes=0 sizeBytes=72} {binding=10 buffer=buffer#7 offsetBytes=0 sizeBytes=4} {binding=11 buffer=buffer#8 offsetBytes=0 sizeBytes=4}]
submit serial=1 commandBuffer#0 commandCount=7
  beginRenderPass label="GeoEncoderPass" colorAttachments=[{view=textureView#2 loadOp=Clear storeOp=Store clearColor=(0 0 0 1)}]
  setScissorRect x=0 y=0 width=64 height=64
  setPipeline renderPipeline#0
  setVertexBuffer slot=0 buffer=buffer#2 offsetBytes=0
  setBindGroup index=0 bindGroup=bindGroup#0
  draw vertexCount=6 instanceCount=3 firstVertex=0 firstInstance=0
  endRenderPass
)";
  // clang-format on
  ExpectCaptureEquals(device_.serialize(), kExpected);
}

/// Scene 3: resident fill across two frames with an identical camera and color. Frame 1
/// uploads the geometry, writes the uniform, and builds the cached bind group; frame 2 must
/// record ZERO buffer creates, buffer writes, and bind-group creates for the resident draw -
/// the design 0030 wave-2 steady-state proof, now pinned structurally.
TEST_F(GeoEncoderRecordingTest, ResidentFillSteadyStateSecondFrameCreatesNothing) {
  Path path = PathBuilder().addRect(Box2d({8, 8}, {56, 56})).build();
  const EncodedPath encoded = GeodePathEncoder::encode(path, FillRule::NonZero);
  GeodeResidentSlot slot;

  {
    GeoEncoder frame1 = makeEncoder();
    frame1.clear(css::RGBA(0, 0, 0, 255));
    frame1.fillPathResident(slot, encoded, css::RGBA(0, 255, 0, 255), FillRule::NonZero,
                            /*frameId=*/1);
    frame1.finish();
  }
  const std::string captureAfterFrame1 = device_.serialize();

  GeoEncoder frame2 = makeEncoder();
  frame2.clear(css::RGBA(0, 0, 0, 255));
  frame2.fillPathResident(slot, encoded, css::RGBA(0, 255, 0, 255), FillRule::NonZero,
                          /*frameId=*/2);
  frame2.finish();

  const std::string capture = device_.serialize();

  // Focused steady-state assertion over just the frame-2 slice, so a regression localizes
  // without diffing the full golden: the resident draw re-uses the frame-1 buffer, uniform
  // contents, and bind group.
  ASSERT_THAT(capture.substr(0, captureAfterFrame1.size()), Eq(captureAfterFrame1));
  const std::string frame2Slice = capture.substr(captureAfterFrame1.size());
  EXPECT_THAT(frame2Slice, Not(HasSubstr("createBuffer")));
  EXPECT_THAT(frame2Slice, Not(HasSubstr("writeBuffer")));
  EXPECT_THAT(frame2Slice, Not(HasSubstr("createBindGroup")));

  // clang-format off
  const std::string kExpected = FixturePreamble() + R"(createTextureView textureView#2 label="GeoEncoderTarget" texture=texture#2
createBuffer buffer#1 label="GeodeResidentPath" byteSize=2080 usage=Vertex|Uniform|Storage|CopyDst
writeBuffer buffer#1 offsetBytes=0 byteCount=1792 dataHash=6a848d9cda0d80c1
writeBuffer buffer#1 offsetBytes=1792 byteCount=288 dataHash=03466db091721b49
createBindGroup bindGroup#0 label="GeodeResidentBindGroup" layout=bindGroupLayout#0 entries=[{binding=0 buffer=buffer#1 offsetBytes=1792 sizeBytes=288} {binding=1 buffer=buffer#1 offsetBytes=256 sizeBytes=64} {binding=2 buffer=buffer#1 offsetBytes=512 sizeBytes=120} {binding=3 textureView=textureView#0} {binding=4 sampler=sampler#0} {binding=5 textureView=textureView#1} {binding=6 sampler=sampler#1} {binding=7 buffer=buffer#0 offsetBytes=0 sizeBytes=32} {binding=8 buffer=buffer#1 offsetBytes=768 sizeBytes=64} {binding=9 buffer=buffer#1 offsetBytes=1024 sizeBytes=120} {binding=10 buffer=buffer#1 offsetBytes=1280 sizeBytes=8} {binding=11 buffer=buffer#1 offsetBytes=1536 sizeBytes=8}]
submit serial=1 commandBuffer#0 commandCount=7
  beginRenderPass label="GeoEncoderPass" colorAttachments=[{view=textureView#2 loadOp=Clear storeOp=Store clearColor=(0 0 0 1)}]
  setScissorRect x=0 y=0 width=64 height=64
  setPipeline renderPipeline#0
  setVertexBuffer slot=0 buffer=buffer#1 offsetBytes=0
  setBindGroup index=0 bindGroup=bindGroup#0
  draw vertexCount=6 instanceCount=1 firstVertex=0 firstInstance=0
  endRenderPass
destroy textureView#2
createTextureView textureView#2 label="GeoEncoderTarget" texture=texture#2
submit serial=2 commandBuffer#0 commandCount=7
  beginRenderPass label="GeoEncoderPass" colorAttachments=[{view=textureView#2 loadOp=Clear storeOp=Store clearColor=(0 0 0 1)}]
  setScissorRect x=0 y=0 width=64 height=64
  setPipeline renderPipeline#0
  setVertexBuffer slot=0 buffer=buffer#1 offsetBytes=0
  setBindGroup index=0 bindGroup=bindGroup#0
  draw vertexCount=6 instanceCount=1 firstVertex=0 firstInstance=0
  endRenderPass
)";
  // clang-format on
  ExpectCaptureEquals(capture, kExpected);
}

/// Scene 4: linear + radial gradient fills through the gradient pipeline.
TEST_F(GeoEncoderRecordingTest, LinearAndRadialGradientFills) {
  Path path = PathBuilder().addRect(Box2d({0, 0}, {64, 64})).build();

  LinearGradientParams::Stop stops[2] = {};
  stops[0].offset = 0.0f;
  stops[0].rgba[0] = 1.0f;
  stops[0].rgba[3] = 1.0f;
  stops[1].offset = 1.0f;
  stops[1].rgba[2] = 1.0f;
  stops[1].rgba[3] = 1.0f;

  LinearGradientParams linear;
  linear.startGrad = Vector2d(0.0, 0.0);
  linear.endGrad = Vector2d(64.0, 0.0);
  linear.gradientFromPath = Transform2d();
  linear.spreadMode = 0;
  linear.stops = std::span<const LinearGradientParams::Stop>(stops, 2);

  RadialGradientParams radial;
  radial.center = Vector2d(32.0, 32.0);
  radial.focalCenter = Vector2d(32.0, 32.0);
  radial.radius = 32.0;
  radial.focalRadius = 0.0;
  radial.gradientFromPath = Transform2d();
  radial.spreadMode = 0;
  radial.stops = std::span<const RadialGradientParams::Stop>(stops, 2);

  GeoEncoder encoder = makeEncoder();
  encoder.clear(css::RGBA(0, 0, 0, 255));
  encoder.fillPathLinearGradient(path, linear, FillRule::NonZero);
  encoder.fillPathRadialGradient(path, radial, FillRule::NonZero);
  encoder.finish();

  // clang-format off
  const std::string kExpected = FixturePreamble() + R"(createTextureView textureView#2 label="GeoEncoderTarget" texture=texture#2
createBuffer buffer#1 label="GeodeVertexArena" byteSize=65536 usage=Vertex|CopyDst
writeBuffer buffer#1 offsetBytes=0 byteCount=120 dataHash=fbf4bbac31777005
createBuffer buffer#2 label="GeodeBandArena" byteSize=65536 usage=Storage|CopyDst
writeBuffer buffer#2 offsetBytes=0 byteCount=64 dataHash=253e812ff00ed57d
createBuffer buffer#3 label="GeodeCurveArena" byteSize=65536 usage=Storage|CopyDst
writeBuffer buffer#3 offsetBytes=0 byteCount=120 dataHash=3d898b38307ace45
createBuffer buffer#4 label="GeodeVBandArena" byteSize=65536 usage=Storage|CopyDst
writeBuffer buffer#4 offsetBytes=0 byteCount=64 dataHash=6b2b24e03919c97d
createBuffer buffer#5 label="GeodeVCurveArena" byteSize=65536 usage=Storage|CopyDst
writeBuffer buffer#5 offsetBytes=0 byteCount=120 dataHash=100db67feef86005
createBuffer buffer#6 label="GeodeHGridArena" byteSize=65536 usage=Storage|CopyDst
writeBuffer buffer#6 offsetBytes=0 byteCount=8 dataHash=08cd4c29d1e47d34
createBuffer buffer#7 label="GeodeVGridArena" byteSize=65536 usage=Storage|CopyDst
writeBuffer buffer#7 offsetBytes=0 byteCount=8 dataHash=08cd4c29d1e47d34
createBuffer buffer#8 label="GeodeUniformArena" byteSize=65536 usage=Uniform|CopyDst
writeBuffer buffer#8 offsetBytes=0 byteCount=592 dataHash=1d02ac1d06038ca1
createBindGroup bindGroup#0 label="GeodeGradientBindGroup" layout=bindGroupLayout#1 entries=[{binding=0 buffer=buffer#8 offsetBytes=0 sizeBytes=592} {binding=1 buffer=buffer#2 offsetBytes=0 sizeBytes=64} {binding=2 buffer=buffer#3 offsetBytes=0 sizeBytes=120} {binding=3 textureView=textureView#1} {binding=4 sampler=sampler#1} {binding=5 buffer=buffer#4 offsetBytes=0 sizeBytes=64} {binding=6 buffer=buffer#5 offsetBytes=0 sizeBytes=120} {binding=7 buffer=buffer#6 offsetBytes=0 sizeBytes=8} {binding=8 buffer=buffer#7 offsetBytes=0 sizeBytes=8}]
writeBuffer buffer#1 offsetBytes=120 byteCount=120 dataHash=fbf4bbac31777005
writeBuffer buffer#2 offsetBytes=256 byteCount=64 dataHash=253e812ff00ed57d
writeBuffer buffer#3 offsetBytes=256 byteCount=120 dataHash=3d898b38307ace45
writeBuffer buffer#4 offsetBytes=256 byteCount=64 dataHash=6b2b24e03919c97d
writeBuffer buffer#5 offsetBytes=256 byteCount=120 dataHash=100db67feef86005
writeBuffer buffer#6 offsetBytes=256 byteCount=8 dataHash=08cd4c29d1e47d34
writeBuffer buffer#7 offsetBytes=256 byteCount=8 dataHash=08cd4c29d1e47d34
writeBuffer buffer#8 offsetBytes=768 byteCount=592 dataHash=abc5cda2cf3b3e98
createBindGroup bindGroup#1 label="GeodeGradientBindGroup" layout=bindGroupLayout#1 entries=[{binding=0 buffer=buffer#8 offsetBytes=768 sizeBytes=592} {binding=1 buffer=buffer#2 offsetBytes=256 sizeBytes=64} {binding=2 buffer=buffer#3 offsetBytes=256 sizeBytes=120} {binding=3 textureView=textureView#1} {binding=4 sampler=sampler#1} {binding=5 buffer=buffer#4 offsetBytes=256 sizeBytes=64} {binding=6 buffer=buffer#5 offsetBytes=256 sizeBytes=120} {binding=7 buffer=buffer#6 offsetBytes=256 sizeBytes=8} {binding=8 buffer=buffer#7 offsetBytes=256 sizeBytes=8}]
submit serial=1 commandBuffer#0 commandCount=10
  beginRenderPass label="GeoEncoderPass" colorAttachments=[{view=textureView#2 loadOp=Clear storeOp=Store clearColor=(0 0 0 1)}]
  setScissorRect x=0 y=0 width=64 height=64
  setPipeline renderPipeline#1
  setVertexBuffer slot=0 buffer=buffer#1 offsetBytes=0
  setBindGroup index=0 bindGroup=bindGroup#0
  draw vertexCount=6 instanceCount=1 firstVertex=0 firstInstance=0
  setVertexBuffer slot=0 buffer=buffer#1 offsetBytes=120
  setBindGroup index=0 bindGroup=bindGroup#1
  draw vertexCount=6 instanceCount=1 firstVertex=0 firstInstance=0
  endRenderPass
)";
  // clang-format on
  ExpectCaptureEquals(device_.serialize(), kExpected);
}

/// Scene 5: pattern fill sampling a 4x4 tile texture uploaded through
/// GeodeTextureEncoder::uploadRgba8Texture (256-byte row padding on the staging path).
TEST_F(GeoEncoderRecordingTest, PatternFill) {
  constexpr uint32_t kTileDim = 4;
  std::array<uint8_t, kTileDim * kTileDim * 4> tilePixels{};
  for (size_t i = 0; i < tilePixels.size(); i += 4) {
    tilePixels[i + 0] = 255;
    tilePixels[i + 3] = 255;
  }
  const gpu::Texture tile =
      GeodeTextureEncoder::uploadRgba8Texture(context_, tilePixels.data(), kTileDim, kTileDim);
  ASSERT_TRUE(tile.isValid());

  Path path = PathBuilder().addRect(Box2d({16, 16}, {48, 48})).build();

  GeoEncoder encoder = makeEncoder();
  encoder.clear(css::RGBA(0, 0, 0, 255));
  GeoEncoder::PatternPaint paint;
  paint.tile = &tile;
  paint.tileSize = Vector2d(4.0, 4.0);
  paint.patternFromPath = Transform2d();
  paint.opacity = 1.0;
  encoder.fillPathPattern(path, FillRule::NonZero, paint);
  encoder.finish();

  // clang-format off
  const std::string kExpected = FixturePreamble() + R"(createTexture texture#3 label="GeodeUploadedImage" size=4x4 format=RGBA8Unorm usage=Sampled|CopyDst sampleCount=1
writeTexture texture#3 offsetBytes=0 bytesPerRow=256 rowsPerImage=4 writeSize=4x4 byteCount=1024 dataHash=4741e416be9c9605
createTextureView textureView#2 label="GeoEncoderTarget" texture=texture#2
createSampler sampler#5 label="GeoEncoderPatternSampler" magFilter=Linear minFilter=Linear addressModeU=Repeat addressModeV=Repeat
createTextureView textureView#3 label="GeoEncoderPatternTileView" texture=texture#3
createBuffer buffer#1 label="GeodeVertexArena" byteSize=65536 usage=Vertex|CopyDst
writeBuffer buffer#1 offsetBytes=0 byteCount=120 dataHash=36ff4236ea0065f5
createBuffer buffer#2 label="GeodeBandArena" byteSize=65536 usage=Storage|CopyDst
writeBuffer buffer#2 offsetBytes=0 byteCount=32 dataHash=c6fd1e2a3b928a36
createBuffer buffer#3 label="GeodeCurveArena" byteSize=65536 usage=Storage|CopyDst
writeBuffer buffer#3 offsetBytes=0 byteCount=72 dataHash=b4ead2ffbd88266c
createBuffer buffer#4 label="GeodeVBandArena" byteSize=65536 usage=Storage|CopyDst
writeBuffer buffer#4 offsetBytes=0 byteCount=32 dataHash=c6fd1e2a3b928a36
createBuffer buffer#5 label="GeodeVCurveArena" byteSize=65536 usage=Storage|CopyDst
writeBuffer buffer#5 offsetBytes=0 byteCount=72 dataHash=467c6868522c325c
createBuffer buffer#6 label="GeodeHGridArena" byteSize=65536 usage=Storage|CopyDst
writeBuffer buffer#6 offsetBytes=0 byteCount=4 dataHash=4d25767f9dce13f5
createBuffer buffer#7 label="GeodeVGridArena" byteSize=65536 usage=Storage|CopyDst
writeBuffer buffer#7 offsetBytes=0 byteCount=4 dataHash=4d25767f9dce13f5
createBuffer buffer#8 label="GeodeUniformArena" byteSize=65536 usage=Uniform|CopyDst
writeBuffer buffer#8 offsetBytes=0 byteCount=288 dataHash=42f5100eeb765678
createBindGroup bindGroup#0 label="GeodeBindGroup" layout=bindGroupLayout#0 entries=[{binding=0 buffer=buffer#8 offsetBytes=0 sizeBytes=288} {binding=1 buffer=buffer#2 offsetBytes=0 sizeBytes=32} {binding=2 buffer=buffer#3 offsetBytes=0 sizeBytes=72} {binding=3 textureView=textureView#3} {binding=4 sampler=sampler#5} {binding=5 textureView=textureView#1} {binding=6 sampler=sampler#1} {binding=7 buffer=buffer#0 offsetBytes=0 sizeBytes=32} {binding=8 buffer=buffer#4 offsetBytes=0 sizeBytes=32} {binding=9 buffer=buffer#5 offsetBytes=0 sizeBytes=72} {binding=10 buffer=buffer#6 offsetBytes=0 sizeBytes=4} {binding=11 buffer=buffer#7 offsetBytes=0 sizeBytes=4}]
submit serial=1 commandBuffer#0 commandCount=7
  beginRenderPass label="GeoEncoderPass" colorAttachments=[{view=textureView#2 loadOp=Clear storeOp=Store clearColor=(0 0 0 1)}]
  setScissorRect x=0 y=0 width=64 height=64
  setPipeline renderPipeline#0
  setVertexBuffer slot=0 buffer=buffer#1 offsetBytes=0
  setBindGroup index=0 bindGroup=bindGroup#0
  draw vertexCount=6 instanceCount=1 firstVertex=0 firstInstance=0
  endRenderPass
)";
  // clang-format on
  ExpectCaptureEquals(device_.serialize(), kExpected);
}

/// Scene 6: drawImage of a small ImageResource - exercises uploadRgba8Texture plus the
/// textured-quad image pipeline path.
TEST_F(GeoEncoderRecordingTest, DrawImage) {
  svg::ImageResource image;
  image.width = 2;
  image.height = 2;
  image.data = {
      255, 0, 255, 255, 255, 0, 255, 255,  //
      255, 0, 255, 255, 255, 0, 255, 255,
  };

  GeoEncoder encoder = makeEncoder();
  encoder.clear(css::RGBA(0, 0, 0, 255));
  encoder.drawImage(image, Box2d({16.0, 16.0}, {48.0, 48.0}), /*opacity=*/1.0,
                    /*pixelated=*/true);
  encoder.finish();

  // clang-format off
  const std::string kExpected = FixturePreamble() + R"(createTextureView textureView#2 label="GeoEncoderTarget" texture=texture#2
createTexture texture#3 label="GeodeUploadedImage" size=2x2 format=RGBA8Unorm usage=Sampled|CopyDst sampleCount=1
writeTexture texture#3 offsetBytes=0 bytesPerRow=256 rowsPerImage=2 writeSize=2x2 byteCount=512 dataHash=63511b1117efd585
createBuffer buffer#1 label="GeodeImageBlitUniforms" byteSize=160 usage=Uniform|CopyDst
writeBuffer buffer#1 offsetBytes=0 byteCount=160 dataHash=d374f8e44bfb04e8
createTextureView textureView#3 label="GeodeImageBlitView" texture=texture#3
createBindGroup bindGroup#0 label="GeodeImageBlitBindGroup" layout=bindGroupLayout#2 entries=[{binding=0 buffer=buffer#1 offsetBytes=0 sizeBytes=160} {binding=1 sampler=sampler#3} {binding=2 textureView=textureView#3} {binding=3 textureView=textureView#3} {binding=4 textureView=textureView#3} {binding=5 textureView=textureView#3} {binding=6 sampler=sampler#4}]
submit serial=1 commandBuffer#0 commandCount=7
  beginRenderPass label="GeoEncoderPass" colorAttachments=[{view=textureView#2 loadOp=Clear storeOp=Store clearColor=(0 0 0 1)}]
  setScissorRect x=0 y=0 width=64 height=64
  setPipeline renderPipeline#2
  setPipeline renderPipeline#2
  setBindGroup index=0 bindGroup=bindGroup#0
  draw vertexCount=6 instanceCount=1 firstVertex=0 firstInstance=0
  endRenderPass
)";
  // clang-format on
  ExpectCaptureEquals(device_.serialize(), kExpected);
}

/// Scene 7: blitFullTarget from an offscreen 64x64 layer texture with opacity - the
/// popIsolatedLayer source-over composite path.
TEST_F(GeoEncoderRecordingTest, BlitFullTargetWithOpacity) {
  const gpu::Texture layer = GetResultOrFail(device_.createTexture(gpu::TextureDescriptor{
      "OffscreenLayer", gpu::Extent2d{kSize, kSize}, gpu::TextureFormat::RGBA8Unorm,
      gpu::TextureUsage::RenderAttachment | gpu::TextureUsage::Sampled}));

  GeoEncoder encoder = makeEncoder();
  encoder.setLoadPreserve();
  encoder.blitFullTarget(layer, /*opacity=*/0.5);
  encoder.finish();

  // clang-format off
  const std::string kExpected = FixturePreamble() + R"(createTexture texture#3 label="OffscreenLayer" size=64x64 format=RGBA8Unorm usage=RenderAttachment|Sampled sampleCount=1
createTextureView textureView#2 label="GeoEncoderTarget" texture=texture#2
createBuffer buffer#1 label="GeodeImageBlitUniforms" byteSize=160 usage=Uniform|CopyDst
writeBuffer buffer#1 offsetBytes=0 byteCount=160 dataHash=ae9283365fffd409
createTextureView textureView#3 label="GeodeImageBlitView" texture=texture#3
createBindGroup bindGroup#0 label="GeodeImageBlitBindGroup" layout=bindGroupLayout#2 entries=[{binding=0 buffer=buffer#1 offsetBytes=0 sizeBytes=160} {binding=1 sampler=sampler#2} {binding=2 textureView=textureView#3} {binding=3 textureView=textureView#3} {binding=4 textureView=textureView#3} {binding=5 textureView=textureView#3} {binding=6 sampler=sampler#4}]
submit serial=1 commandBuffer#0 commandCount=7
  beginRenderPass label="GeoEncoderPass" colorAttachments=[{view=textureView#2 loadOp=Load storeOp=Store clearColor=(0 0 0 0)}]
  setScissorRect x=0 y=0 width=64 height=64
  setPipeline renderPipeline#2
  setPipeline renderPipeline#2
  setBindGroup index=0 bindGroup=bindGroup#0
  draw vertexCount=6 instanceCount=1 firstVertex=0 firstInstance=0
  endRenderPass
)";
  // clang-format on
  ExpectCaptureEquals(device_.serialize(), kExpected);
}

/// Scene 8: mix-blend-mode blit in SHARED-CommandEncoder mode, mirroring RendererGeode's
/// frame flow (design 0030 M3 + Phase 3d): copyTextureToTexture snapshots the backdrop while
/// no pass is open, a GeoEncoder over the shared encoder records the blend blit, and the
/// caller finishes + submits the shared encoder exactly once.
TEST_F(GeoEncoderRecordingTest, SharedEncoderBlendBlitWithBackdropCopy) {
  const gpu::Texture layer = GetResultOrFail(device_.createTexture(gpu::TextureDescriptor{
      "BlendLayer", gpu::Extent2d{kSize, kSize}, gpu::TextureFormat::RGBA8Unorm,
      gpu::TextureUsage::RenderAttachment | gpu::TextureUsage::Sampled}));
  const gpu::Texture snapshot = GetResultOrFail(device_.createTexture(gpu::TextureDescriptor{
      "BlendDstSnapshot", gpu::Extent2d{kSize, kSize}, gpu::TextureFormat::RGBA8Unorm,
      gpu::TextureUsage::Sampled | gpu::TextureUsage::CopyDst}));

  std::unique_ptr<gpu::CommandEncoder> sharedEncoder =
      GetResultOrFail(device_.createCommandEncoder());
  ASSERT_NE(sharedEncoder, nullptr);

  // Snapshot the backdrop before any pass opens (mid-pass copies are rejected).
  ASSERT_THAT(sharedEncoder->copyTextureToTexture(target_, snapshot, gpu::Extent2d{kSize, kSize}),
              gpu::IsOk());

  GeoEncoder encoder(context_, fillPipeline_, gradientPipeline_, imagePipeline_, target_,
                     gpu::Extent2d{kSize, kSize}, *sharedEncoder);
  encoder.setLoadPreserve();
  encoder.blitFullTargetBlended(layer, snapshot, /*blendMode=*/2, /*opacity=*/0.5);
  encoder.finish();  // Shared mode: only ends the open pass.

  auto commandBuffer = sharedEncoder->finish();
  ASSERT_THAT(commandBuffer, gpu::HasResult());
  ASSERT_THAT(device_.submit(std::move(commandBuffer).result()), gpu::HasResult());

  // clang-format off
  const std::string kExpected = FixturePreamble() + R"(createTexture texture#3 label="BlendLayer" size=64x64 format=RGBA8Unorm usage=RenderAttachment|Sampled sampleCount=1
createTexture texture#4 label="BlendDstSnapshot" size=64x64 format=RGBA8Unorm usage=Sampled|CopyDst sampleCount=1
createTextureView textureView#2 label="GeoEncoderTarget" texture=texture#2
createBuffer buffer#1 label="GeodeImageBlitUniforms" byteSize=160 usage=Uniform|CopyDst
writeBuffer buffer#1 offsetBytes=0 byteCount=160 dataHash=4c8eaec6862a048b
createTextureView textureView#3 label="GeodeImageBlitView" texture=texture#3
createTextureView textureView#4 label="GeodeImageBlitView" texture=texture#4
createBindGroup bindGroup#0 label="GeodeImageBlitBindGroup" layout=bindGroupLayout#2 entries=[{binding=0 buffer=buffer#1 offsetBytes=0 sizeBytes=160} {binding=1 sampler=sampler#2} {binding=2 textureView=textureView#3} {binding=3 textureView=textureView#3} {binding=4 textureView=textureView#4} {binding=5 textureView=textureView#3} {binding=6 sampler=sampler#4}]
submit serial=1 commandBuffer#0 commandCount=8
  copyTextureToTexture src=texture#2 dst=texture#4 copySize=64x64
  beginRenderPass label="GeoEncoderPass" colorAttachments=[{view=textureView#2 loadOp=Load storeOp=Store clearColor=(0 0 0 0)}]
  setScissorRect x=0 y=0 width=64 height=64
  setPipeline renderPipeline#2
  setPipeline renderPipeline#2
  setBindGroup index=0 bindGroup=bindGroup#0
  draw vertexCount=6 instanceCount=1 firstVertex=0 firstInstance=0
  endRenderPass
)";
  // clang-format on
  ExpectCaptureEquals(device_.serialize(), kExpected);
}

}  // namespace

}  // namespace donner::geode
