#!/usr/bin/env python3
"""Generates the machine-readable GPU runtime inventory manifests for design doc 0053.

Scans the git-tracked source tree and produces four JSON manifests under
tools/gpu_inventory/manifests/:

- gpu_operations.json: every file using the WebGPU wrapper (wgpu:: identifiers,
  wgpuXxx C entry points, WGPU* C types) plus the GPU operation methods it calls.
- shader_features.json: every WGSL shader (standalone .wgsl files and inline
  R"wgsl(...)" literals) with entry points, bindings, and language features.
- editor_integration.json: editor files that touch the GPU surface (wgpu types,
  the ImGui WebGPU backend, editor GPU feature defines).
- rust_dependencies.json: all tracked Rust sources and Cargo metadata, Rust build
  rule references, and Rust-built prebuilt archive declarations.

The scan is intentionally lexical: it over-approximates so that any new GPU
operation, shader feature, or Rust dependency edge changes at least one manifest.
Adding such a use without regenerating the manifests fails the `--check` step in
the Lint workflow.

Usage:
  python3 tools/gpu_inventory/generate_gpu_manifests.py            # regenerate
  python3 tools/gpu_inventory/generate_gpu_manifests.py --check    # verify up to date
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

MANIFEST_DIR = Path(__file__).resolve().parent / "manifests"
REPO_ROOT = Path(__file__).resolve().parents[2]

GENERATOR_NOTE = (
    "Generated by tools/gpu_inventory/generate_gpu_manifests.py; do not edit by hand. "
    "Regenerate with: python3 tools/gpu_inventory/generate_gpu_manifests.py"
)

# WebGPU wrapper / C API token patterns. `wgpu::` identifiers come from the
# vendored webgpu.hpp wrapper, `wgpuXxx` are wgpu-native C entry points, and
# `WGPUXxx` are C ABI types.
WGPU_CPP_RE = re.compile(r"\bwgpu::([A-Za-z_][A-Za-z0-9_]*)")
WGPU_C_FUNC_RE = re.compile(r"\bwgpu[A-Z][A-Za-z0-9_]*\b")
WGPU_C_TYPE_RE = re.compile(r"\bWGPU[A-Z][A-Za-z0-9_]*\b")
IMGUI_WGPU_RE = re.compile(r"\bImGui_ImplWGPU_[A-Za-z0-9_]*\b")
EDITOR_WGPU_DEFINE_RE = re.compile(r"\bDONNER_EDITOR_WGPU\b")

# GPU operation methods, per the design 0053 current-state inventory. Matched as
# `.method(` inside files that already reference the WebGPU wrapper, so generic
# names like `draw` do not pick up unrelated call sites. This is a curated,
# labeled view; completeness of the ratchet does not depend on it because every
# scanned file also records a content hash, so any edit to a wgpu-using file
# forces a manifest regeneration. `RenderPassEncoder::end` is intentionally not
# tracked lexically (`.end(` is ambiguous with container `end()`); pass lifetime
# coverage comes from beginRenderPass/beginComputePass plus the content hash.
OPERATION_METHODS = (
    "beginComputePass",
    "beginRenderPass",
    "configure",
    "copyBufferToBuffer",
    "copyBufferToTexture",
    "copyTextureToBuffer",
    "copyTextureToTexture",
    "createBindGroup",
    "createBindGroupLayout",
    "createBuffer",
    "createCommandEncoder",
    "createComputePipeline",
    "createPipelineLayout",
    "createRenderPipeline",
    "createSampler",
    "createShaderModule",
    "createTexture",
    "createView",
    "destroy",
    "dispatchWorkgroups",
    "draw",
    "drawIndexed",
    "finish",
    "getCapabilities",
    "getConstMappedRange",
    "getCurrentTexture",
    "getQueue",
    "hasFeature",
    "mapAsync",
    "onSubmittedWorkDone",
    "poll",
    "present",
    "release",
    "requestAdapter",
    "requestDevice",
    "setBindGroup",
    "setIndexBuffer",
    "setPipeline",
    "setScissorRect",
    "setVertexBuffer",
    "setViewport",
    "submit",
    "unmap",
    "writeBuffer",
    "writeTexture",
)
OPERATION_RE = re.compile(r"\.\s*(" + "|".join(OPERATION_METHODS) + r")\s*\(")

# WGSL parsing patterns. Entry-point and binding attributes may appear in any
# order, so both patterns match an attribute blob and the fields are extracted
# from it afterwards.
WGSL_ENTRY_RE = re.compile(
    r"((?:@(?:vertex|fragment|compute)|@workgroup_size\([^)]*\))"
    r"(?:\s*(?:@(?:vertex|fragment|compute)|@workgroup_size\([^)]*\)))*)"
    r"\s*fn\s+([A-Za-z_][A-Za-z0-9_]*)",
    re.DOTALL,
)
WGSL_ENTRY_STAGE_RE = re.compile(r"@(vertex|fragment|compute)\b")
WGSL_WORKGROUP_SIZE_RE = re.compile(r"@workgroup_size\(([^)]*)\)")
WGSL_BINDING_RE = re.compile(
    r"((?:@group\(\d+\)|@binding\(\d+\))\s*(?:@group\(\d+\)|@binding\(\d+\))\s*)"
    r"var\s*(<[^>]*>)?\s*([A-Za-z_][A-Za-z0-9_]*)\s*:\s*([^;]+);"
)
WGSL_GROUP_RE = re.compile(r"@group\((\d+)\)")
WGSL_BINDING_INDEX_RE = re.compile(r"@binding\((\d+)\)")
WGSL_BUILTIN_RE = re.compile(r"@builtin\(([A-Za-z_][A-Za-z0-9_]*)\)")
WGSL_STRUCT_RE = re.compile(r"\bstruct\s+([A-Za-z_][A-Za-z0-9_]*)")
# Inline WGSL raw strings, with or without an `identifier =` assignment prefix;
# unassigned literals (e.g. passed directly as an argument) get an index-based
# manifest key.
INLINE_WGSL_RE = re.compile(
    r"(?:([A-Za-z_][A-Za-z0-9_]*)\s*=\s*)?R\"wgsl\((.*?)\)wgsl\"", re.DOTALL
)

# WGSL language features tracked as simple word-boundary tokens. The shader IR
# (design 0053 phase 2) may only claim support for features present here.
WGSL_FEATURE_TOKENS = (
    "abs",
    "array",
    "atomic",
    "break",
    "ceil",
    "clamp",
    "const",
    "continue",
    "cos",
    "cross",
    "discard",
    "distance",
    "dot",
    "exp",
    "exp2",
    "floor",
    "fma",
    "for",
    "fract",
    "fwidth",
    "if",
    "length",
    "let",
    "log",
    "log2",
    "loop",
    "mat2x2f",
    "mat3x3f",
    "mat4x4f",
    "max",
    "min",
    "mix",
    "normalize",
    "pow",
    "return",
    "round",
    "saturate",
    "select",
    "sign",
    "sin",
    "smoothstep",
    "sqrt",
    "step",
    "switch",
    "tan",
    "textureDimensions",
    "textureLoad",
    "textureSample",
    "textureSampleLevel",
    "textureStore",
    "var",
    "while",
    "workgroupBarrier",
)

# Files that participate in the build graph, for Rust build-edge scanning.
# `BUILD.<name>` covers overlay build files applied to external archives (e.g.
# third_party/BUILD.wgpu_native_platform) and `WORKSPACE.<name>` covers
# WORKSPACE.bazel/WORKSPACE.bzlmod. Kept in sync with
# check_no_rust_dependencies.py.
BUILD_GRAPH_FILE_RE = re.compile(
    r"(^|/)(MODULE\.bazel(\.lock)?|BUILD(\.[^/]+)?|WORKSPACE(\.[^/]+)?|[^/]+\.bzl|\.bazelrc)$"
)
RUST_BUILD_TOKENS = (
    "cargo_bazel",
    "crate_universe",
    "rules_rust",
    "rust_binary",
    "rust_library",
    "rust_static_library",
    "rust_toolchains",
)
WGPU_ARCHIVE_TOKENS = ("gfx-rs/wgpu-native", "wgpu_native_")
WGPU_NATIVE_VERSION_RE = re.compile(r"_WGPU_NATIVE_VERSION\s*=\s*\"([^\"]+)\"")


def git_tracked_files(repo_root: Path) -> list[str]:
    """Returns all git-tracked paths (repo-relative, sorted)."""
    output = subprocess.check_output(
        ["git", "ls-files", "-z"], cwd=repo_root, text=True, encoding="utf-8"
    )
    return sorted(p for p in output.split("\0") if p)


def read_text_or_none(path: Path) -> str | None:
    """Reads a file as UTF-8, returning None for binary/undecodable content."""
    try:
        return path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError):
        return None


def scan_wgpu_tokens(text: str) -> dict[str, object]:
    """Extracts WebGPU wrapper/C-API tokens and operation methods from source text."""
    result: dict[str, object] = {}
    cpp_tokens = sorted({m.group(1) for m in WGPU_CPP_RE.finditer(text)})
    c_funcs = sorted(set(WGPU_C_FUNC_RE.findall(text)))
    c_types = sorted(set(WGPU_C_TYPE_RE.findall(text)))
    if cpp_tokens:
        result["wgpuCppTokens"] = cpp_tokens
    if c_funcs:
        result["wgpuCFunctions"] = c_funcs
    if c_types:
        result["wgpuCTypes"] = c_types
    if result:
        operations = sorted({m.group(1) for m in OPERATION_RE.finditer(text)})
        if operations:
            result["operations"] = operations
    return result


def scan_wgsl(text: str) -> dict[str, object]:
    """Extracts entry points, bindings, and language features from WGSL source."""
    entry_points = []
    for attributes, name in WGSL_ENTRY_RE.findall(text):
        stage_match = WGSL_ENTRY_STAGE_RE.search(attributes)
        if not stage_match:
            continue
        entry: dict[str, object] = {"name": name, "stage": stage_match.group(1)}
        workgroup_match = WGSL_WORKGROUP_SIZE_RE.search(attributes)
        if workgroup_match:
            entry["workgroupSize"] = [s.strip() for s in workgroup_match.group(1).split(",")]
        entry_points.append(entry)
    entry_points.sort(key=lambda e: (e["stage"], e["name"]))

    bindings = []
    for attributes, address_space, name, binding_type in WGSL_BINDING_RE.findall(text):
        group_match = WGSL_GROUP_RE.search(attributes)
        binding_match = WGSL_BINDING_INDEX_RE.search(attributes)
        if not group_match or not binding_match:
            continue
        binding_entry = {
            "group": int(group_match.group(1)),
            "binding": int(binding_match.group(1)),
            "name": name,
            "type": re.sub(r"\s+", " ", binding_type.strip()),
        }
        if address_space:
            binding_entry["addressSpace"] = address_space.strip("<>").strip()
        bindings.append(binding_entry)
    bindings.sort(key=lambda b: (b["group"], b["binding"]))

    features = sorted(
        token
        for token in WGSL_FEATURE_TOKENS
        if re.search(r"\b" + re.escape(token) + r"\b", text)
    )
    builtins = sorted(set(WGSL_BUILTIN_RE.findall(text)))
    structs = sorted(set(WGSL_STRUCT_RE.findall(text)))

    return {
        "bindings": bindings,
        "builtins": builtins,
        "entryPoints": entry_points,
        "features": features,
        "lineCount": text.count("\n") + (0 if text.endswith("\n") or not text else 1),
        "structs": structs,
    }


def is_first_party_source(path: str) -> bool:
    """True for first-party C++/ObjC++ sources (everything outside vendored code)."""
    if path.startswith(("third_party/", "external/", "bazel-")):
        return False
    if "/third_party/" in path:
        return False
    return path.endswith((".h", ".cc", ".mm"))


def content_sha256(text: str) -> str:
    """Content hash recorded per manifest entry so any edit to a GPU-using file
    forces a manifest regeneration, independent of the curated token lists."""
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def build_gpu_operations_manifest(files: dict[str, str]) -> dict[str, object]:
    """Builds the per-file WebGPU token/operation manifest for first-party sources."""
    per_file: dict[str, object] = {}
    for path in sorted(files):
        if not is_first_party_source(path):
            continue
        tokens = scan_wgpu_tokens(files[path])
        if tokens:
            tokens["sha256"] = content_sha256(files[path])
            per_file[path] = tokens

    # Patched third-party WebGPU integration code (e.g. the ImGui WebGPU backend
    # patches) is part of the design 0053 inventory even though it lives outside
    # first-party sources.
    patches = sorted(
        path
        for path in files
        if path.endswith(".patch") and ("wgpu" in files[path] or "WGPU" in files[path])
    )
    return {"_comment": GENERATOR_NOTE, "files": per_file, "wgpuPatchFiles": patches}


def build_shader_features_manifest(files: dict[str, str]) -> dict[str, object]:
    """Builds the WGSL shader manifest, including inline R"wgsl(...)" literals."""
    shaders: dict[str, object] = {}
    for path in sorted(files):
        if path.endswith(".wgsl") and not path.startswith("third_party/"):
            shaders[path] = scan_wgsl(files[path])
        elif is_first_party_source(path):
            for index, match in enumerate(INLINE_WGSL_RE.finditer(files[path])):
                name = match.group(1) or f"inline{index}"
                shaders[f"{path}#{name}"] = scan_wgsl(match.group(2))
    return {"_comment": GENERATOR_NOTE, "shaders": shaders}


def build_editor_integration_manifest(files: dict[str, str]) -> dict[str, object]:
    """Builds the editor GPU integration manifest (wgpu + ImGui WebGPU surface)."""
    per_file: dict[str, object] = {}
    for path in sorted(files):
        if not path.startswith("donner/editor/"):
            continue
        if not path.endswith((".h", ".cc", ".mm")):
            continue
        text = files[path]
        entry = scan_wgpu_tokens(text)
        imgui_tokens = sorted(set(IMGUI_WGPU_RE.findall(text)))
        if imgui_tokens:
            entry["imguiWgpuTokens"] = imgui_tokens
        if EDITOR_WGPU_DEFINE_RE.search(text):
            entry["usesEditorWgpuDefine"] = True
        if entry:
            entry["sha256"] = content_sha256(text)
            per_file[path] = entry
    return {"_comment": GENERATOR_NOTE, "files": per_file}


def is_rust_source_path(path: str) -> bool:
    """True for Rust source and Cargo metadata paths."""
    return path.endswith(".rs") or path.endswith(("Cargo.toml", "Cargo.lock"))


def build_rust_dependencies_manifest(
    files: dict[str, str], allowlist_prefixes: list[str]
) -> dict[str, object]:
    """Builds the Rust dependency manifest: sources, build edges, prebuilt archives."""
    allowlisted = []
    active = []
    for path in sorted(files):
        if not is_rust_source_path(path):
            continue
        if any(path.startswith(prefix) for prefix in allowlist_prefixes):
            allowlisted.append(path)
        else:
            active.append(path)

    build_edges: dict[str, list[str]] = {}
    wgpu_archive_sites: dict[str, object] = {}
    for path in sorted(files):
        if not BUILD_GRAPH_FILE_RE.search(path):
            continue
        text = files[path]
        rust_tokens = sorted(t for t in RUST_BUILD_TOKENS if t in text)
        if rust_tokens:
            build_edges[path] = rust_tokens
        archive_tokens = sorted(t for t in WGPU_ARCHIVE_TOKENS if t in text)
        if archive_tokens:
            site: dict[str, object] = {"tokens": archive_tokens}
            version_match = WGPU_NATIVE_VERSION_RE.search(text)
            if version_match:
                site["wgpuNativeVersion"] = version_match.group(1)
            wgpu_archive_sites[path] = site

    return {
        "_comment": GENERATOR_NOTE,
        "allowlistPrefixes": sorted(allowlist_prefixes),
        "allowlistedRustSources": allowlisted,
        "activeRustSources": active,
        "rustBuildEdges": build_edges,
        "rustBuiltArchiveSites": wgpu_archive_sites,
    }


def load_allowlist_prefixes(allowlist_path: Path) -> list[str]:
    """Loads the inert-reference allowlist path prefixes."""
    data = json.loads(allowlist_path.read_text(encoding="utf-8"))
    return list(data["inertReferencePrefixes"])


def build_all_manifests(
    files: dict[str, str], allowlist_prefixes: list[str]
) -> dict[str, dict[str, object]]:
    """Builds all four manifests from a path -> content mapping."""
    return {
        "gpu_operations.json": build_gpu_operations_manifest(files),
        "shader_features.json": build_shader_features_manifest(files),
        "editor_integration.json": build_editor_integration_manifest(files),
        "rust_dependencies.json": build_rust_dependencies_manifest(files, allowlist_prefixes),
    }


def render_manifest(manifest: dict[str, object]) -> str:
    """Serializes a manifest deterministically (sorted keys, 2-space indent, LF)."""
    return json.dumps(manifest, indent=2, sort_keys=True) + "\n"


def collect_repo_files(repo_root: Path) -> dict[str, str]:
    """Reads all git-tracked text files relevant to the manifest scans."""
    files: dict[str, str] = {}
    for path in git_tracked_files(repo_root):
        interesting = (
            is_first_party_source(path)
            or path.startswith("donner/")
            or path.endswith((".wgsl", ".patch"))
            or is_rust_source_path(path)
            or BUILD_GRAPH_FILE_RE.search(path) is not None
        )
        if not interesting:
            continue
        text = read_text_or_none(repo_root / path)
        if text is not None:
            files[path] = text
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify the checked-in manifests match a fresh regeneration.",
    )
    parser.add_argument("--root", type=Path, default=REPO_ROOT, help="Repository root to scan.")
    args = parser.parse_args()

    allowlist_path = args.root / "tools/gpu_inventory/rust_allowlist.json"
    manifest_dir = args.root / "tools/gpu_inventory/manifests"

    files = collect_repo_files(args.root)
    manifests = build_all_manifests(files, load_allowlist_prefixes(allowlist_path))

    stale = []
    for name, manifest in manifests.items():
        rendered = render_manifest(manifest)
        target = manifest_dir / name
        if args.check:
            existing = target.read_text(encoding="utf-8") if target.exists() else None
            if existing != rendered:
                stale.append(name)
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(rendered, encoding="utf-8")
            print(f"wrote {target.relative_to(args.root)}")

    if args.check and stale:
        print(
            "GPU inventory manifests are stale: " + ", ".join(sorted(stale)),
            file=sys.stderr,
        )
        print(
            "Regenerate with: python3 tools/gpu_inventory/generate_gpu_manifests.py",
            file=sys.stderr,
        )
        return 1
    if args.check:
        print("GPU inventory manifests are up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
