load("@rules_cc//cc:defs.bzl", "cc_library")
load("//build_defs:package.bzl", "donner_package")

cc_library(
    name = "graph",
    srcs = [
        "Reference.cc",
    ],
    hdrs = [
        "RecursionGuard.h",
        "Reference.h",
    ],
    visibility = [
        "//donner/svg:__subpackages__",
    ],
    deps = [
        "//donner/base",
        "//donner/svg/components:attached_id_lookup",
    ],
)

donner_package()
