#include <gtest/gtest.h>

#include <filesystem>
#include <fstream>
#include <string>

#include "donner/base/ParseWarningSink.h"
#include "donner/svg/parser/SVGParser.h"
#include "donner/svg/renderer/tests/ImageComparisonTestFixture.h"

/**
 * @file
 *
 * Golden-image tests for the Geode (WebGPU + Slug) backend, curated for the
 * skeleton stage.
 *
 * The full `renderer_tests` target is gated off Geode because stroke,
 * gradient, text, image, and filter features are all stubbed. This file
 * lists only SVGs that use nothing but solid-color path fills, so we can
 * begin comparing Geode output against goldens as each feature lands.
 *
 * **Geode uses its own goldens** under `testdata/golden/geode/`, *not*
 * the Skia/tiny-skia goldens. Slug's per-pixel winding-number coverage
 * differs at sub-pixel edges from scanline rasterizer AA, so a single
 * shared golden would force either constantly-inflated thresholds or
 * spurious CI failures. Per-backend goldens let us enforce strict
 * identity (`threshold=0`, `maxMismatchedPixels=0`,
 * `includeAntiAliasingDifferences`) and catch *Geode's own* regressions.
 *
 * To (re)generate all Geode goldens:
 * ```sh
 * UPDATE_GOLDEN_IMAGES_DIR=$(bazel info workspace) \
 *   bazel run --config=geode //donner/svg/renderer/tests:renderer_geode_golden_tests
 * ```
 *
 * If a test fails, do *not* bump the threshold — it means `GeodePathEncoder`,
 * the Slug shaders, or `GeoEncoder`'s state setup has regressed. Dig in.
 */

namespace donner::svg {
namespace {

/// Strict identity check: every pixel must match exactly, including AA
/// edges. Appropriate for per-backend goldens that were generated by the
/// same backend we're testing.
ImageComparisonParams strictGeodeParams() {
  return ImageComparisonParams::WithThreshold(0.0f, 0).includeAntiAliasingDifferences();
}

class RendererGeodeGoldenTests : public ImageComparisonTestFixture {
protected:
  SVGDocument loadSVG(const char* filename, parser::SVGParser::Options options = {}) {
    std::ifstream file(filename);
    EXPECT_TRUE(file) << "Failed to open file: " << filename;
    if (!file) {
      return SVGDocument();
    }

    file.seekg(0, std::ios::end);
    const std::streamsize fileLength = file.tellg();
    file.seekg(0);

    std::string fileData;
    fileData.resize(fileLength);
    file.read(fileData.data(), fileLength);

    ParseWarningSink disabled = ParseWarningSink::Disabled();
    auto maybeResult = parser::SVGParser::ParseSVG(fileData, disabled, options);
    EXPECT_FALSE(maybeResult.hasError()) << "Parse Error: " << maybeResult.error();
    if (maybeResult.hasError()) {
      return SVGDocument();
    }

    return std::move(maybeResult.result());
  }

  void compareWithGeodeGolden(const char* svgFilename, const char* geodeGoldenFilename,
                              ImageComparisonParams params = strictGeodeParams()) {
    SVGDocument document = loadSVG(svgFilename);
    params.enableGoldenUpdateFromEnv();
    renderAndCompare(document, svgFilename, geodeGoldenFilename, params);
  }
};

// ----------------------------------------------------------------------------
// Pure solid-fill SVGs. Expected to round-trip through Geode exactly, since
// the goldens were captured from Geode itself.
// ----------------------------------------------------------------------------

/// 2x2 canvas, one cubic Bézier filled with a solid color. Minimal-footprint
/// regression target for cubic-to-quadratic decomposition.
TEST_F(RendererGeodeGoldenTests, MinimalClosedCubic2x2) {
  compareWithGeodeGolden(
      "donner/svg/renderer/testdata/minimal_closed_cubic_2x2.svg",
      "donner/svg/renderer/testdata/golden/geode/minimal_closed_cubic_2x2.png",
      strictGeodeParams().setCanvasSize(10, 10));
}

/// 5x3 canvas, similar to the 2x2 case.
TEST_F(RendererGeodeGoldenTests, MinimalClosedCubic5x3) {
  compareWithGeodeGolden(
      "donner/svg/renderer/testdata/minimal_closed_cubic_5x3.svg",
      "donner/svg/renderer/testdata/golden/geode/minimal_closed_cubic_5x3.png",
      strictGeodeParams().setCanvasSize(10, 6));
}

/// Large solid-colored lightning bolt path. Pure `<path fill="#faa21b">`, no
/// stroke / gradient / filter. Good mid-sized regression target.
TEST_F(RendererGeodeGoldenTests, BigLightningGlowNoFilterCrop) {
  compareWithGeodeGolden(
      "donner/svg/renderer/testdata/big_lightning_glow_no_filter_crop.svg",
      "donner/svg/renderer/testdata/golden/geode/big_lightning_glow_no_filter_crop.png");
}

/// Classic lion. Hundreds of solid-color polygons, no strokes or gradients.
/// The best "does Geode actually work on real content" stress test we have.
TEST_F(RendererGeodeGoldenTests, Lion) {
  compareWithGeodeGolden("donner/svg/renderer/testdata/lion.svg",
                         "donner/svg/renderer/testdata/golden/geode/lion.png");
}

/// Edzample animation (first frame). Solid-color paths, no stroke/gradient.
TEST_F(RendererGeodeGoldenTests, Edzample) {
  compareWithGeodeGolden("donner/svg/renderer/testdata/Edzample_Anim3.svg",
                         "donner/svg/renderer/testdata/golden/geode/Edzample_Anim3.png");
}

}  // namespace
}  // namespace donner::svg
