#include <gtest/gtest.h>

#include "donner/svg/renderer/tests/RendererTestUtils.h"
#include "donner/svg/tests/ParserTestUtils.h"

/// @file
/// Time-sampled golden render checks for the SMIL animation slice 1. Each test renders a small SVG
/// at fixed document times and compares the result against a hand-verifiable ASCII golden (black
/// fill renders as '@', background as '.'). Covers before/mid/after phases, freeze vs remove fill,
/// remove revert across time samples of one live document, transform animation, and repeatCount.

namespace donner::svg {
namespace {

/// Parse a fragment with experimental (animation) elements enabled, on a 16x16 canvas.
SVGDocument parseAnimated(std::string_view fragment) {
  parser::SVGParser::Options options;
  options.enableExperimental = true;
  return instantiateSubtree(fragment, options, Vector2i(16, 16));
}

}  // namespace

TEST(RendererAnimation, GeometryGrowFreeze) {
  // <animate> on rect width from 4 to 12 over 2s, frozen after.
  SVGDocument document = parseAnimated(R"(
    <rect x="0" y="0" width="4" height="16" fill="black">
      <animate attributeName="width" from="4" to="12" begin="0s" dur="2s" fill="freeze" />
    </rect>
  )");

  // t=0 (before/start): width = 4.
  document.setTime(0.0);
  EXPECT_TRUE(RendererTestUtils::renderToAsciiImage(document).matches(R"(
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    )"));

  // t=1 (mid, 50%): width = 8.
  document.setTime(1.0);
  EXPECT_TRUE(RendererTestUtils::renderToAsciiImage(document).matches(R"(
    @@@@@@@@........
    @@@@@@@@........
    @@@@@@@@........
    @@@@@@@@........
    @@@@@@@@........
    @@@@@@@@........
    @@@@@@@@........
    @@@@@@@@........
    @@@@@@@@........
    @@@@@@@@........
    @@@@@@@@........
    @@@@@@@@........
    @@@@@@@@........
    @@@@@@@@........
    @@@@@@@@........
    @@@@@@@@........
    )"));

  // t=3 (after, frozen): width = 12.
  document.setTime(3.0);
  EXPECT_TRUE(RendererTestUtils::renderToAsciiImage(document).matches(R"(
    @@@@@@@@@@@@....
    @@@@@@@@@@@@....
    @@@@@@@@@@@@....
    @@@@@@@@@@@@....
    @@@@@@@@@@@@....
    @@@@@@@@@@@@....
    @@@@@@@@@@@@....
    @@@@@@@@@@@@....
    @@@@@@@@@@@@....
    @@@@@@@@@@@@....
    @@@@@@@@@@@@....
    @@@@@@@@@@@@....
    @@@@@@@@@@@@....
    @@@@@@@@@@@@....
    @@@@@@@@@@@@....
    @@@@@@@@@@@@....
    )"));
}

TEST(RendererAnimation, GeometryRemoveReverts) {
  // Default fill="remove": after the active interval the width reverts to its base (4). Rendering
  // the same live document at t=1 (active) then t=3 (after) exercises the base-component
  // backup/restore path.
  SVGDocument document = parseAnimated(R"(
    <rect x="0" y="0" width="4" height="16" fill="black">
      <animate attributeName="width" from="4" to="12" begin="0s" dur="2s" />
    </rect>
  )");

  // t=1 (active, 50%): width = 8.
  document.setTime(1.0);
  EXPECT_TRUE(RendererTestUtils::renderToAsciiImage(document).matches(R"(
    @@@@@@@@........
    @@@@@@@@........
    @@@@@@@@........
    @@@@@@@@........
    @@@@@@@@........
    @@@@@@@@........
    @@@@@@@@........
    @@@@@@@@........
    @@@@@@@@........
    @@@@@@@@........
    @@@@@@@@........
    @@@@@@@@........
    @@@@@@@@........
    @@@@@@@@........
    @@@@@@@@........
    @@@@@@@@........
    )"));

  // t=3 (after, remove): reverts to base width = 4.
  document.setTime(3.0);
  EXPECT_TRUE(RendererTestUtils::renderToAsciiImage(document).matches(R"(
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    )"));
}

TEST(RendererAnimation, TransformTranslateFreeze) {
  // <animateTransform> translate from 0 to 8 over 2s, frozen after. A 4-wide bar slides right.
  SVGDocument document = parseAnimated(R"(
    <rect x="0" y="0" width="4" height="16" fill="black">
      <animateTransform attributeName="transform" type="translate"
                        from="0 0" to="8 0" begin="0s" dur="2s" fill="freeze" />
    </rect>
  )");

  // t=0: translate(0) -> columns 0-3.
  document.setTime(0.0);
  EXPECT_TRUE(RendererTestUtils::renderToAsciiImage(document).matches(R"(
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    )"));

  // t=1 (mid): translate(4) -> columns 4-7.
  document.setTime(1.0);
  EXPECT_TRUE(RendererTestUtils::renderToAsciiImage(document).matches(R"(
    ....@@@@........
    ....@@@@........
    ....@@@@........
    ....@@@@........
    ....@@@@........
    ....@@@@........
    ....@@@@........
    ....@@@@........
    ....@@@@........
    ....@@@@........
    ....@@@@........
    ....@@@@........
    ....@@@@........
    ....@@@@........
    ....@@@@........
    ....@@@@........
    )"));

  // t=3 (after, frozen): translate(8) -> columns 8-11.
  document.setTime(3.0);
  EXPECT_TRUE(RendererTestUtils::renderToAsciiImage(document).matches(R"(
    ........@@@@....
    ........@@@@....
    ........@@@@....
    ........@@@@....
    ........@@@@....
    ........@@@@....
    ........@@@@....
    ........@@@@....
    ........@@@@....
    ........@@@@....
    ........@@@@....
    ........@@@@....
    ........@@@@....
    ........@@@@....
    ........@@@@....
    ........@@@@....
    )"));
}

TEST(RendererAnimation, RepeatCount) {
  // width 0->16 over 2s, repeated twice. The frame at t=0.5 (iteration 0, 25%) and t=2.5
  // (iteration 1, 25%) must be identical (width = 4), demonstrating the repeat.
  SVGDocument document = parseAnimated(R"(
    <rect x="0" y="0" width="0" height="16" fill="black">
      <animate attributeName="width" from="0" to="16" begin="0s" dur="2s"
               repeatCount="2" fill="freeze" />
    </rect>
  )");

  // t=0.5: iteration 0, 25% -> width = 4.
  document.setTime(0.5);
  EXPECT_TRUE(RendererTestUtils::renderToAsciiImage(document).matches(R"(
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    )"));

  // t=2.5: iteration 1, 25% -> width = 4 again (repeat).
  document.setTime(2.5);
  EXPECT_TRUE(RendererTestUtils::renderToAsciiImage(document).matches(R"(
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    @@@@............
    )"));

  // t=5: after active duration (4s), frozen at final width = 16.
  document.setTime(5.0);
  EXPECT_TRUE(RendererTestUtils::renderToAsciiImage(document).matches(R"(
    @@@@@@@@@@@@@@@@
    @@@@@@@@@@@@@@@@
    @@@@@@@@@@@@@@@@
    @@@@@@@@@@@@@@@@
    @@@@@@@@@@@@@@@@
    @@@@@@@@@@@@@@@@
    @@@@@@@@@@@@@@@@
    @@@@@@@@@@@@@@@@
    @@@@@@@@@@@@@@@@
    @@@@@@@@@@@@@@@@
    @@@@@@@@@@@@@@@@
    @@@@@@@@@@@@@@@@
    @@@@@@@@@@@@@@@@
    @@@@@@@@@@@@@@@@
    @@@@@@@@@@@@@@@@
    @@@@@@@@@@@@@@@@
    )"));
}

}  // namespace donner::svg
