#include <gtest/gtest.h>

#include "donner/svg/renderer/tests/RendererTestUtils.h"

namespace donner::svg {
namespace {

TEST(RendererAsciiTests, RectAscii) {
  const AsciiImage generatedAscii = RendererTestUtils::renderToAsciiImage(R"(
        <rect width="8" height="8" fill="black" />
        )");

  EXPECT_TRUE(generatedAscii.matches(R"(
        @@@@@@@@........
        @@@@@@@@........
        @@@@@@@@........
        @@@@@@@@........
        @@@@@@@@........
        @@@@@@@@........
        @@@@@@@@........
        @@@@@@@@........
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        )"));
}

}  // namespace
}  // namespace donner::svg
