#include <gtest/gtest.h>

#include "donner/svg/renderer/tests/RendererTestUtils.h"

namespace donner::svg {
namespace {

TEST(RendererAsciiTests, RectAscii) {
  const AsciiImage generatedAscii = RendererTestUtils::renderToAsciiImage(R"(
        <rect width="8" height="8" fill="black" />
        )");

  EXPECT_TRUE(generatedAscii.matches(R"(
        @@@@@@@@........
        @@@@@@@@........
        @@@@@@@@........
        @@@@@@@@........
        @@@@@@@@........
        @@@@@@@@........
        @@@@@@@@........
        @@@@@@@@........
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        )"));
}

TEST(RendererAsciiTests, TinySkiaMismatchDoesNotFallBackToDefault) {
  if (ActiveRendererBackend() != RendererBackend::TinySkia) {
    GTEST_SKIP() << "TinySkia-specific matcher regression";
  }

  const AsciiImage geodeImage{"geode\n"};
  EXPECT_FALSE(geodeImage.matchBackend().defaultPattern("geode\n").tinySkia("tiny-skia\n"));
}

}  // namespace
}  // namespace donner::svg
