#include <gtest/gtest.h>

#include <filesystem>
#include <fstream>
#include <string>

#include "donner/base/ParseWarningSink.h"
#include "donner/svg/parser/SVGParser.h"
#include "donner/svg/renderer/tests/ImageComparisonTestFixture.h"

/**
 * @file
 *
 * Golden-image tests for the Geode (WebGPU + Slug) backend, curated for the
 * skeleton stage.
 *
 * The full `renderer_tests` target is gated off Geode because stroke,
 * gradient, text, image, and filter features are all stubbed. This file
 * lists only SVGs that use nothing but solid-color path fills, so we can
 * begin comparing Geode output against goldens as each feature lands.
 *
 * **Geode uses its own goldens** under `testdata/golden/geode/`, *not*
 * the Skia/tiny-skia goldens. Slug's per-pixel winding-number coverage
 * differs at sub-pixel edges from scanline rasterizer AA, so a single
 * shared golden would force either constantly-inflated thresholds or
 * spurious CI failures. Per-backend goldens let us enforce strict
 * identity (`threshold=0`, `maxMismatchedPixels=0`,
 * `includeAntiAliasingDifferences`) and catch *Geode's own* regressions.
 *
 * To (re)generate all Geode goldens:
 * ```sh
 * UPDATE_GOLDEN_IMAGES_DIR=$(bazel info workspace) \
 *   bazel run --config=geode //donner/svg/renderer/tests:renderer_geode_golden_tests
 * ```
 *
 * If a test fails, do *not* bump the threshold — it means `GeodePathEncoder`,
 * the Slug shaders, or `GeoEncoder`'s state setup has regressed. Dig in.
 */

namespace donner::svg {
namespace {

/// Strict identity check: every pixel must match exactly, including AA
/// edges. Appropriate for per-backend goldens that were generated by the
/// same backend we're testing.
ImageComparisonParams strictGeodeParams() {
  return ImageComparisonParams::WithThreshold(0.0f, 0).includeAntiAliasingDifferences();
}

class RendererGeodeGoldenTests : public ImageComparisonTestFixture {
protected:
  SVGDocument loadSVG(const char* filename, parser::SVGParser::Options options = {}) {
    std::ifstream file(filename);
    EXPECT_TRUE(file) << "Failed to open file: " << filename;
    if (!file) {
      return SVGDocument();
    }

    file.seekg(0, std::ios::end);
    const std::streamsize fileLength = file.tellg();
    file.seekg(0);

    std::string fileData;
    fileData.resize(fileLength);
    file.read(fileData.data(), fileLength);

    ParseWarningSink disabled = ParseWarningSink::Disabled();
    auto maybeResult = parser::SVGParser::ParseSVG(fileData, disabled, options);
    EXPECT_FALSE(maybeResult.hasError()) << "Parse Error: " << maybeResult.error();
    if (maybeResult.hasError()) {
      return SVGDocument();
    }

    return std::move(maybeResult.result());
  }

  void compareWithGeodeGolden(const char* svgFilename, const char* geodeGoldenFilename,
                              ImageComparisonParams params = strictGeodeParams()) {
    SVGDocument document = loadSVG(svgFilename);
    params.enableGoldenUpdateFromEnv();
    renderAndCompare(document, svgFilename, geodeGoldenFilename, params);
  }
};

// ----------------------------------------------------------------------------
// Pure solid-fill SVGs. Expected to round-trip through Geode exactly, since
// the goldens were captured from Geode itself.
// ----------------------------------------------------------------------------

/// 2x2 canvas, one cubic Bézier filled with a solid color. Minimal-footprint
/// regression target for cubic-to-quadratic decomposition.
TEST_F(RendererGeodeGoldenTests, MinimalClosedCubic2x2) {
  compareWithGeodeGolden(
      "donner/svg/renderer/testdata/minimal_closed_cubic_2x2.svg",
      "donner/svg/renderer/testdata/golden/geode/minimal_closed_cubic_2x2.png",
      strictGeodeParams().setCanvasSize(10, 10));
}

/// 5x3 canvas, similar to the 2x2 case.
TEST_F(RendererGeodeGoldenTests, MinimalClosedCubic5x3) {
  compareWithGeodeGolden(
      "donner/svg/renderer/testdata/minimal_closed_cubic_5x3.svg",
      "donner/svg/renderer/testdata/golden/geode/minimal_closed_cubic_5x3.png",
      strictGeodeParams().setCanvasSize(10, 6));
}

/// Large solid-colored lightning bolt path. Pure `<path fill="#faa21b">`, no
/// stroke / gradient / filter. Good mid-sized regression target.
TEST_F(RendererGeodeGoldenTests, BigLightningGlowNoFilterCrop) {
  compareWithGeodeGolden(
      "donner/svg/renderer/testdata/big_lightning_glow_no_filter_crop.svg",
      "donner/svg/renderer/testdata/golden/geode/big_lightning_glow_no_filter_crop.png");
}

/// Classic lion. Hundreds of solid-color polygons, no strokes or gradients.
/// The best "does Geode actually work on real content" stress test we have.
TEST_F(RendererGeodeGoldenTests, Lion) {
  compareWithGeodeGolden("donner/svg/renderer/testdata/lion.svg",
                         "donner/svg/renderer/testdata/golden/geode/lion.png");
}

/// Edzample animation (first frame). Solid-color paths, no stroke/gradient.
TEST_F(RendererGeodeGoldenTests, Edzample) {
  compareWithGeodeGolden("donner/svg/renderer/testdata/Edzample_Anim3.svg",
                         "donner/svg/renderer/testdata/golden/geode/Edzample_Anim3.png");
}

// ----------------------------------------------------------------------------
// Solid-color stroke SVGs. Exercise Path::strokeToFill through the Geode
// pipeline.
//
// Visual inspection during bring-up surfaced several bugs in `strokeToFill`
// that make stroke golden coverage narrower than we'd like. Each has a
// follow-up task; re-enable the corresponding tests once the root cause is
// fixed. Deferred:
//
//   - **Dashes** — stroking_dasharray / stroking_dashoffset /
//     stroking_pathlength / stroking_complex. `strokeToFill` ignores
//     `dashArray`; the Geode adapter warns once in verbose mode and draws
//     the undashed stroke. Needs dash support in `strokeToFill`.
//
//   - **Round / square caps** — stroking_linecap. Visual output renders all
//     three cap styles as butt. Either `emitCap` isn't producing the extra
//     geometry or it's being produced but mis-rendered. (Task #34.)
//
//   - **Sharp concave corners on open subpaths** — stroking_linejoin. The
//     inverted-V path hits `emitJoin`'s "inside-turn" branch, which just
//     draws a line across the two offset endpoints. That creates a
//     self-intersecting polygon that neither NonZero nor EvenOdd renders
//     cleanly. Needs proper inner-corner intersection handling in
//     `Path::strokeToFill`. (Task #32.)
//
//   - **Curved flattened strokes on closed subpaths** — rect2 (rounded
//     rect), ellipse1, skew1 (rounded parallelogram), quadbezier1,
//     size-too-large. These produce diagonal streaks inside the stroke
//     ring. Root cause is not yet identified — possibly flattened inner
//     contours with crossing-count inconsistencies that defeat EvenOdd, or
//     a Slug band encoder issue with multi-subpath inputs. (Task #33.)
//
//   - **Mixed stroke/miter artifacts** — polygon, stroking_miterlimit.
//     Visually show small extra extensions beyond the shape boundary.
//     Probably related to the same curve-stroke root cause as above.
//
// The tests below are the ones that passed visual inspection — pure
// straight-line open subpaths with butt caps. They exercise the stroke
// pipeline end to end (including `Path::strokeToFill` for open subpaths)
// even if coverage is narrow.
// ----------------------------------------------------------------------------

/// Polyline with solid stroke — exercises open-subpath stroke with default
/// (butt) caps and straight-segment bevel joins.
TEST_F(RendererGeodeGoldenTests, Polyline) {
  compareWithGeodeGolden("donner/svg/renderer/testdata/polyline.svg",
                         "donner/svg/renderer/testdata/golden/geode/polyline.png");
}

/// `stroke-width` across a range of values on horizontal lines. Butt caps,
/// no curves, no joins — smallest possible exercise of variable widths.
TEST_F(RendererGeodeGoldenTests, StrokingStrokewidth) {
  compareWithGeodeGolden("donner/svg/renderer/testdata/stroking_strokewidth.svg",
                         "donner/svg/renderer/testdata/golden/geode/stroking_strokewidth.png");
}

}  // namespace
}  // namespace donner::svg
