name: Editor WASM

on:
  schedule:
    - cron: "18 7 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.19.0
        with:
          bazelisk-cache: true
          disk-cache: editor-wasm-${{ runner.os }}
          repository-cache: true
          external-cache: true
          cache-save: true

      - name: Build editor wasm package
        run: |
          bazelisk build --config=editor-wasm //donner/editor/wasm:wasm_web_package
